// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "github.com/apimatic/go-core-runtime/https"
)

// createAuthenticationFromConfig returns a map of auth interfaces that provides authentications for API calls.
func createAuthenticationFromConfig(
    oAuth2SandboxManager func() *OAuth2SandboxManager,
    oAuth2ProductionManager func() *OAuth2ProductionManager) map[string]https.AuthInterface {
    return map[string]https.AuthInterface {
        "OAuth2-sandbox": oAuth2SandboxManager(),
        "OAuth2-production": oAuth2ProductionManager(),
    }
}
