// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
)

const UserAgent = "APIMATIC 3.0"
// Client is an interface representing the main client for accessing configuration and controllers.
type ClientInterface interface {
    Configuration() Configuration
    CloneWithConfiguration(options ...ConfigurationOptions) ClientInterface
    InstallmentPlanController() *InstallmentPlanController
    OAuthAuthorizationController() *OAuthAuthorizationController
    OAuth2SandboxManager() *OAuth2SandboxManager
    OAuth2ProductionManager() *OAuth2ProductionManager
}

// client is an implementation of the Client interface.
type client struct {
    callBuilderFactory           https.CallBuilderFactory
    configuration                Configuration
    installmentPlanController    InstallmentPlanController
    oAuthAuthorizationController OAuthAuthorizationController
    oAuth2SandboxManager         OAuth2SandboxManager
    oAuth2ProductionManager      OAuth2ProductionManager
}

// NewClient is the constructor for creating a new client instance.
// It takes a Configuration object as a parameter and returns the Client interface.
func NewClient(configuration Configuration) ClientInterface {
    client := &client{
        configuration: configuration,
    }
    
    client.callBuilderFactory = callBuilderHandler(
    	func(server string) string {
    		if server == "" {
    			server = "default"
    		}
    		return getBaseUri(Server(server), client.configuration)
    	},
    	createAuthenticationFromConfig(func() *OAuth2SandboxManager { return client.OAuth2SandboxManager() }, func() *OAuth2ProductionManager { return client.OAuth2ProductionManager() }),
    	https.NewHttpClient(configuration.HttpConfiguration()),
    	configuration.httpConfiguration.RetryConfiguration(),
    	https.Indexed,
        withUserAgent(UserAgent),
    )
    
    baseController := NewBaseController(client)
    client.installmentPlanController = *NewInstallmentPlanController(*baseController)
    client.oAuthAuthorizationController = *NewOAuthAuthorizationController(*baseController)
    client.oAuth2SandboxManager = *newOAuth2SandboxManager(configuration.oAuth2SandboxCredentials, client.oAuthAuthorizationController)
    client.oAuth2ProductionManager = *newOAuth2ProductionManager(configuration.oAuth2ProductionCredentials, client.oAuthAuthorizationController)
    return client
}

// Configuration returns the configuration instance of the client.
func (c *client) Configuration() Configuration {
    return c.configuration
}

// CloneWithConfiguration returns a new copy with the provided options of the configuration instance of the client.
func (c *client) CloneWithConfiguration(options ...ConfigurationOptions) ClientInterface {
    return NewClient(c.configuration.cloneWithOptions(options...))
}

// InstallmentPlanController returns the installmentPlanController instance of the client.
func (c *client) InstallmentPlanController() *InstallmentPlanController {
    return &c.installmentPlanController
}

// OAuthAuthorizationController returns the oAuthAuthorizationController instance of the client.
func (c *client) OAuthAuthorizationController() *OAuthAuthorizationController {
    return &c.oAuthAuthorizationController
}

// OAuth2SandboxManager returns the oAuth2SandboxManager instance of the client.
func (c *client) OAuth2SandboxManager() *OAuth2SandboxManager {
    return &c.oAuth2SandboxManager
}

// OAuth2ProductionManager returns the oAuth2ProductionManager instance of the client.
func (c *client) OAuth2ProductionManager() *OAuth2ProductionManager {
    return &c.oAuth2ProductionManager
}

// GetCallBuilder returns the CallBuilderFactory used by the client.
func (c *client) GetCallBuilder() https.CallBuilderFactory {
    return c.callBuilderFactory
}

// getBaseUri returns the base URI based on the server and configuration.
func getBaseUri(
    server Server,
    configuration Configuration) string {
    if configuration.Environment() == Environment(PRODUCTION) {
        if server == Server(ENUMDEFAULT) {
            return "https://web-api-v3.sandbox.splitit.com/"
        }
        if server == Server(ACCESSTOKENSERVER) {
            return "https://id.sandbox.splitit.com/connect"
        }
        if server == Server(ACCESSTOKENSERVER1) {
            return "https://id.splitit.com/connect"
        }
    }
    if configuration.Environment() == Environment(ENVIRONMENT2) {
        if server == Server(ENUMDEFAULT) {
            return "https://web-api-v3.splitit.com/"
        }
        if server == Server(ACCESSTOKENSERVER) {
            return "https://id.sandbox.splitit.com/connect"
        }
        if server == Server(ACCESSTOKENSERVER1) {
            return "https://id.splitit.com/connect"
        }
    }
    return "TODO: Select a valid server."
}

// clientOptions is a function type representing options for the client.
type clientOptions func(cb https.CallBuilder)

// callBuilderHandler creates the call builder factory with various options.
func callBuilderHandler(
    baseUrlProvider func(server string) string,
    auth map[string]https.AuthInterface,
    httpClient https.HttpClient,
    retryConfig RetryConfiguration,
    arraySerializationOption https.ArraySerializationOption,
    opts ...clientOptions) https.CallBuilderFactory {
    callBuilderFactory := https.CreateCallBuilderFactory(baseUrlProvider, auth, httpClient, retryConfig, arraySerializationOption)
    return tap(callBuilderFactory, opts...)
}

// tap is a utility function to apply client options to the call builder factory.
func tap(
    callBuilderFactory https.CallBuilderFactory,
    opts ...clientOptions) https.CallBuilderFactory {
    return func(ctx context.Context, httpMethod, path string) https.CallBuilder {
    	callBuilder := callBuilderFactory(ctx, httpMethod, path)
    	for _, opt := range opts {
    		opt(callBuilder)
    	}
    	return callBuilder
    }
}

// withUserAgent is an option to add a user agent header to the HTTP request.
func withUserAgent(userAgent string) clientOptions {
    f := func(request *http.Request) *http.Request {
    	request.Header.Set("user-agent", userAgent)
    	return request
    }
    return func(cb https.CallBuilder) {
    	cb.InterceptRequest(f)
    }
}
