// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "os"
)

// ConfigurationOptions represents a function type that can be used to apply options to the Configuration struct.
type ConfigurationOptions func(*Configuration)

// Configuration holds configuration settings.
type Configuration struct {
    environment                 Environment
    httpConfiguration           HttpConfiguration
    oAuth2SandboxCredentials    OAuth2SandboxCredentials
    oAuth2ProductionCredentials OAuth2ProductionCredentials
}

// newConfiguration creates a new Configuration with the provided options.
func newConfiguration(options ...ConfigurationOptions) Configuration {
    config := Configuration{}
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// cloneWithOptions provides configuration with the provided options.
func (config Configuration) cloneWithOptions(options ...ConfigurationOptions) Configuration {
    for _, option := range options {
        option(&config)
    }
    return config
}

// WithEnvironment is an option that sets the Environment in the Configuration.
func WithEnvironment(environment Environment) ConfigurationOptions {
    return func(c *Configuration) {
        c.environment = environment
    }
}

// WithHttpConfiguration is an option that sets the HttpConfiguration in the Configuration.
func WithHttpConfiguration(httpConfiguration HttpConfiguration) ConfigurationOptions {
    return func(c *Configuration) {
        c.httpConfiguration = httpConfiguration
    }
}

// WithOAuth2SandboxCredentials is an option that sets the OAuth2SandboxCredentials in the Configuration.
func WithOAuth2SandboxCredentials(oAuth2SandboxCredentials OAuth2SandboxCredentials) ConfigurationOptions {
    return func(c *Configuration) {
        c.oAuth2SandboxCredentials = oAuth2SandboxCredentials
    }
}

// WithOAuth2ProductionCredentials is an option that sets the OAuth2ProductionCredentials in the Configuration.
func WithOAuth2ProductionCredentials(oAuth2ProductionCredentials OAuth2ProductionCredentials) ConfigurationOptions {
    return func(c *Configuration) {
        c.oAuth2ProductionCredentials = oAuth2ProductionCredentials
    }
}

// Environment returns the environment from the Configuration.
func (c Configuration) Environment() Environment {
    return c.environment
}

// HttpConfiguration returns the httpConfiguration from the Configuration.
func (c Configuration) HttpConfiguration() HttpConfiguration {
    return c.httpConfiguration
}

// OAuth2SandboxCredentials returns the oAuth2SandboxCredentials from the Configuration.
func (c Configuration) OAuth2SandboxCredentials() OAuth2SandboxCredentials {
    return c.oAuth2SandboxCredentials
}

// OAuth2ProductionCredentials returns the oAuth2ProductionCredentials from the Configuration.
func (c Configuration) OAuth2ProductionCredentials() OAuth2ProductionCredentials {
    return c.oAuth2ProductionCredentials
}

// CreateConfigurationFromEnvironment creates a new Configuration with default settings.
// It also configures various Configuration options.
func CreateConfigurationFromEnvironment(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    environment := os.Getenv("SPLITITWEBAPIV_3_ENVIRONMENT")
    if environment != "" {
        config.environment = Environment(environment)
    }
    oAuthClientId := os.Getenv("SPLITITWEBAPIV_3_O_AUTH_CLIENT_ID")
    if oAuthClientId != "" {
        config.oAuth2SandboxCredentials.oAuthClientId = oAuthClientId
    }
    oAuthClientSecret := os.Getenv("SPLITITWEBAPIV_3_O_AUTH_CLIENT_SECRET")
    if oAuthClientSecret != "" {
        config.oAuth2SandboxCredentials.oAuthClientSecret = oAuthClientSecret
    }
    oAuthClientId2 := os.Getenv("SPLITITWEBAPIV_3_O_AUTH_CLIENT_ID_2")
    if oAuthClientId2 != "" {
        config.oAuth2ProductionCredentials.oAuthClientId = oAuthClientId2
    }
    oAuthClientSecret2 := os.Getenv("SPLITITWEBAPIV_3_O_AUTH_CLIENT_SECRET_2")
    if oAuthClientSecret2 != "" {
        config.oAuth2ProductionCredentials.oAuthClientSecret = oAuthClientSecret2
    }
    for _, option := range options {
        option(&config)
    }
    return config
}

// Server represents available servers.
type Server string

const (
    ENUMDEFAULT        Server = "default"
    ACCESSTOKENSERVER  Server = "access token server"
    ACCESSTOKENSERVER1 Server = "access token server1"
)

// Environment represents available environments.
type Environment string

const (
    PRODUCTION   Environment = "production"
    ENVIRONMENT2 Environment = "environment2"
)

// CreateRetryConfiguration creates a new RetryConfiguration with the provided options.
func CreateRetryConfiguration(options ...RetryConfigurationOptions) RetryConfiguration {
    config := DefaultRetryConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateHttpConfiguration creates a new HttpConfiguration with the provided options.
func CreateHttpConfiguration(options ...HttpConfigurationOptions) HttpConfiguration {
    config := DefaultHttpConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateConfiguration creates a new Configuration with the provided options.
func CreateConfiguration(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}
