// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "splititwebapiv3/errors"
    "splititwebapiv3/models"
)

// InstallmentPlanController represents a controller struct.
type InstallmentPlanController struct {
    baseController
}

// NewInstallmentPlanController creates a new instance of InstallmentPlanController.
// It takes a baseController as a parameter and returns a pointer to the InstallmentPlanController.
func NewInstallmentPlanController(baseController baseController) *InstallmentPlanController {
    installmentPlanController := InstallmentPlanController{baseController: baseController}
    return &installmentPlanController
}

// InstallmentPlanGet takes context, installmentPlanNumber, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanGetResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanGet(
    ctx context.Context,
    installmentPlanNumber string,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanGetResponse],
    error) {
    req := i.prepareRequest(ctx, "GET", "/api/installmentplans/%v")
    req.AppendTemplateParams(installmentPlanNumber)
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    
    var result models.InstallmentPlanGetResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanGetResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanSearch takes context, installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanSearchResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanSearch(
    ctx context.Context,
    installmentPlanNumber models.Optional[string],
    refOrderNumber models.Optional[string],
    extendedParams models.Optional[interface{}],
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanSearchResponse],
    error) {
    req := i.prepareRequest(ctx, "GET", "/api/installmentplans/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    if installmentPlanNumber.IsValueSet() {
        req.QueryParam("installmentPlanNumber", (*installmentPlanNumber.Value()))
    }
    if refOrderNumber.IsValueSet() {
        req.QueryParam("refOrderNumber", (*refOrderNumber.Value()))
    }
    if extendedParams.IsValueSet() {
        req.QueryParam("extendedParams", (*extendedParams.Value()))
    }
    var result models.InstallmentPlanSearchResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanSearchResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanPost takes context, xSplititIdempotencyKey, body, xSplititTestMode, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InitiatePlanResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanPost(
    ctx context.Context,
    xSplititIdempotencyKey string,
    body models.InstallmentPlanInitiateRequest,
    xSplititTestMode models.Optional[models.TestModesEnum],
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InitiatePlanResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/api/installmentplans/initiate")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "", Unmarshaller: errors.NewPlanErrorResponse},
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTestMode.IsValueSet() {
        req.Header("X-Splitit-TestMode", (*xSplititTestMode.Value()))
    }
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    var result models.InitiatePlanResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InitiatePlanResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanPost2 takes context, xSplititIdempotencyKey, body, xSplititTestMode, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanCreateResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanPost2(
    ctx context.Context,
    xSplititIdempotencyKey string,
    body models.InstallmentPlanCreateRequest,
    xSplititTestMode models.Optional[models.TestModesEnum],
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanCreateResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/api/installmentplans")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "", Unmarshaller: errors.NewPlanErrorResponse},
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTestMode.IsValueSet() {
        req.Header("X-Splitit-TestMode", (*xSplititTestMode.Value()))
    }
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    var result models.InstallmentPlanCreateResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanCreateResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanVerifyAuthorization takes context, installmentPlanNumber, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.VerifyAuthorizationResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanVerifyAuthorization(
    ctx context.Context,
    installmentPlanNumber string,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.VerifyAuthorizationResponse],
    error) {
    req := i.prepareRequest(
      ctx,
      "GET",
      "/api/installmentplans/%v/verifyauthorization",
    )
    req.AppendTemplateParams(installmentPlanNumber)
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    
    var result models.VerifyAuthorizationResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.VerifyAuthorizationResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanUpdateOrder takes context, installmentPlanNumber, xSplititIdempotencyKey, body, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanUpdateResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanUpdateOrder(
    ctx context.Context,
    installmentPlanNumber string,
    xSplititIdempotencyKey string,
    body models.InstallmentPlanUpdateRequest,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanUpdateResponse],
    error) {
    req := i.prepareRequest(ctx, "PUT", "/api/installmentplans/%v/updateorder")
    req.AppendTemplateParams(installmentPlanNumber)
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    
    var result models.InstallmentPlanUpdateResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanUpdateResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanUpdateOrder2 takes context, xSplititIdempotencyKey, body, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanUpdateResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanUpdateOrder2(
    ctx context.Context,
    xSplititIdempotencyKey string,
    body models.InstallmentPlanUpdateRequestByIdentifier,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanUpdateResponse],
    error) {
    req := i.prepareRequest(ctx, "PUT", "/api/installmentplans/updateorder")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    var result models.InstallmentPlanUpdateResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanUpdateResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanRefund takes context, installmentPlanNumber, xSplititIdempotencyKey, body, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentPlanRefundResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanRefund(
    ctx context.Context,
    installmentPlanNumber string,
    xSplititIdempotencyKey string,
    body models.InstallmentPlanRefundRequest,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentPlanRefundResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/api/installmentplans/%v/refund")
    req.AppendTemplateParams(installmentPlanNumber)
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    
    var result models.InstallmentPlanRefundResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentPlanRefundResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanCheckEligibility takes context, xSplititIdempotencyKey, body, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.InstallmentsEligibilityResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanCheckEligibility(
    ctx context.Context,
    xSplititIdempotencyKey string,
    body models.CheckInstallmentsEligibilityRequest,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.InstallmentsEligibilityResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/api/installmentplans/check-eligibility")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    req.Header("X-Splitit-IdempotencyKey", xSplititIdempotencyKey)
    req.Header("Content-Type", "application/json-patch+json")
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    req.Json(&body)
    var result models.InstallmentsEligibilityResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstallmentsEligibilityResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// InstallmentPlanGetEligibilityTermsAndCondition takes context, ipn, xSplititTouchPoint as parameters and
// returns an models.ApiResponse with models.EligibilityTermsAndConditionResponse data and
// an error if there was an issue with the request or response.
func (i *InstallmentPlanController) InstallmentPlanGetEligibilityTermsAndCondition(
    ctx context.Context,
    ipn string,
    xSplititTouchPoint models.Optional[string]) (
    models.ApiResponse[models.EligibilityTermsAndConditionResponse],
    error) {
    req := i.prepareRequest(ctx, "GET", "/api/installmentplans/%v/legal")
    req.AppendTemplateParams(ipn)
    req.Authenticate(
        NewOrAuth(
            NewAuth("OAuth2-sandbox"),
            NewAuth("OAuth2-production"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "401": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "403": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "404": {Message: "", Unmarshaller: errors.NewFailedResponse},
        "500": {Message: "", Unmarshaller: errors.NewFailedResponse},
    })
    if xSplititTouchPoint.IsValueSet() {
        req.Header("X-Splitit-TouchPoint", (*xSplititTouchPoint.Value()))
    }
    
    var result models.EligibilityTermsAndConditionResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EligibilityTermsAndConditionResponse](decoder)
    return models.NewApiResponse(result, resp), err
}
