// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "github.com/apimatic/go-core-runtime/testHelper"
    "splititwebapiv3/models"
    "testing"
)

// TestInstallmentPlanControllerTestInstallmentPlanSearch2 tests the behavior of the InstallmentPlanController
func TestInstallmentPlanControllerTestInstallmentPlanSearch2(t *testing.T) {
    ctx := context.Background()
    
    
    
    
    apiResponse, err := installmentPlanController.InstallmentPlanSearch(ctx, models.EmptyOptional[string](), models.EmptyOptional[string](), models.EmptyOptional[interface{}](), models.EmptyOptional[string]())
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","text/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
}

// TestInstallmentPlanControllerTestInstallmentPlanSearch tests the behavior of the InstallmentPlanController
func TestInstallmentPlanControllerTestInstallmentPlanSearch(t *testing.T) {
    ctx := context.Background()
    
    
    
    
    apiResponse, err := installmentPlanController.InstallmentPlanSearch(ctx, models.EmptyOptional[string](), models.EmptyOptional[string](), models.EmptyOptional[interface{}](), models.EmptyOptional[string]())
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","text/plain"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
}

// TestInstallmentPlanControllerTestInstallmentPlanSearch1 tests the behavior of the InstallmentPlanController
func TestInstallmentPlanControllerTestInstallmentPlanSearch1(t *testing.T) {
    ctx := context.Background()
    
    
    
    
    apiResponse, err := installmentPlanController.InstallmentPlanSearch(ctx, models.EmptyOptional[string](), models.EmptyOptional[string](), models.EmptyOptional[interface{}](), models.EmptyOptional[string]())
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
}
