// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "splititwebapiv3/errors"
    "splititwebapiv3/models"
)

// OAuthAuthorizationController represents a controller struct.
type OAuthAuthorizationController struct {
    baseController
}

// NewOAuthAuthorizationController creates a new instance of OAuthAuthorizationController.
// It takes a baseController as a parameter and returns a pointer to the OAuthAuthorizationController.
func NewOAuthAuthorizationController(baseController baseController) *OAuthAuthorizationController {
    oAuthAuthorizationController := OAuthAuthorizationController{baseController: baseController}
    return &oAuthAuthorizationController
}

// RequestTokenOAuth2Sandbox takes context, authorization, scope as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Create a new OAuth 2 token.
func (o *OAuthAuthorizationController) RequestTokenOAuth2Sandbox(
    ctx context.Context,
    authorization string,
    scope *string,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/token")
    
    req.BaseUrl("access token server")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", authorization)
    req.FormParam("grant_type", "client_credentials")
    if scope != nil {
        req.FormParam("scope", *scope)
    }
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}

// RequestTokenOAuth2Production takes context, authorization, scope as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Create a new OAuth 2 token.
func (o *OAuthAuthorizationController) RequestTokenOAuth2Production(
    ctx context.Context,
    authorization string,
    scope *string,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/token")
    
    req.BaseUrl("access token server1")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", authorization)
    req.FormParam("grant_type", "client_credentials")
    if scope != nil {
        req.FormParam("scope", *scope)
    }
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}
