// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "encoding/base64"
    "errors"
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
    "splititwebapiv3/models"
    "time"
)

// OAuth2SandboxCredentials represents the credentials required for `OAuth2-sandbox` authentication.
type OAuth2SandboxCredentials struct {
    oAuthClientId      string
    oAuthClientSecret  string
    oAuthToken         models.OAuthToken
    oAuthScopes        []models.OAuthScopeOAuth2SandboxEnum
    oAuthTokenProvider func (models.OAuthToken, OAuth2SandboxManager) models.OAuthToken
    oAuthOnTokenUpdate func (token models.OAuthToken)
    oAuthClockSkew     int64
}

// NewOAuth2SandboxCredentials creates a new instance of OAuth2SandboxCredentials with provided parameters.
func NewOAuth2SandboxCredentials(
    oAuthClientId string,
    oAuthClientSecret string) OAuth2SandboxCredentials {
    return OAuth2SandboxCredentials {
        oAuthClientId: oAuthClientId,
        oAuthClientSecret: oAuthClientSecret,
        oAuthClockSkew: 0,
    }
}

// WithOAuthClientId sets oAuthClientId in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthClientId(oAuthClientId string) OAuth2SandboxCredentials {
    o.oAuthClientId = oAuthClientId
    return o
}

// WithOAuthClientSecret sets oAuthClientSecret in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthClientSecret(oAuthClientSecret string) OAuth2SandboxCredentials {
    o.oAuthClientSecret = oAuthClientSecret
    return o
}

// WithOAuthToken sets oAuthToken in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthToken(oAuthToken models.OAuthToken) OAuth2SandboxCredentials {
    o.oAuthToken = oAuthToken
    return o
}

// WithOAuthScopes sets oAuthScopes in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthScopes(oAuthScopes []models.OAuthScopeOAuth2SandboxEnum) OAuth2SandboxCredentials {
    o.oAuthScopes = oAuthScopes
    return o
}

// WithOAuthTokenProvider sets oAuthTokenProvider in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthTokenProvider(oAuthTokenProvider func (models.OAuthToken, OAuth2SandboxManager) models.OAuthToken) OAuth2SandboxCredentials {
    o.oAuthTokenProvider = oAuthTokenProvider
    return o
}

// WithOAuthOnTokenUpdate sets oAuthOnTokenUpdate in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthOnTokenUpdate(oAuthOnTokenUpdate func (token models.OAuthToken)) OAuth2SandboxCredentials {
    o.oAuthOnTokenUpdate = oAuthOnTokenUpdate
    return o
}

// WithOAuthClockSkew sets oAuthClockSkew in OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) WithOAuthClockSkew(oAuthClockSkew int64) OAuth2SandboxCredentials {
    o.oAuthClockSkew = oAuthClockSkew
    return o
}

// OAuthClientId returns the oAuthClientId associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthClientId() string {
    return o.oAuthClientId
}

// OAuthClientSecret returns the oAuthClientSecret associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthClientSecret() string {
    return o.oAuthClientSecret
}

// OAuthToken returns the oAuthToken associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthToken() models.OAuthToken {
    return o.oAuthToken
}

// OAuthScopes returns the oAuthScopes associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthScopes() []models.OAuthScopeOAuth2SandboxEnum {
    return o.oAuthScopes
}

// OAuthTokenProvider returns the oAuthTokenProvider associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthTokenProvider() func (models.OAuthToken, OAuth2SandboxManager) models.OAuthToken {
    return o.oAuthTokenProvider
}

// OAuthOnTokenUpdate returns the oAuthOnTokenUpdate associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthOnTokenUpdate() func (token models.OAuthToken) {
    return o.oAuthOnTokenUpdate
}

// OAuthClockSkew returns the oAuthClockSkew associated with the OAuth2SandboxCredentials.
func (o OAuth2SandboxCredentials) OAuthClockSkew() int64 {
    return o.oAuthClockSkew
}

// isTokenValid checks if the provided OAuthToken is valid.
func (o OAuth2SandboxCredentials) isTokenValid() bool {
    return o.OAuthToken().AccessToken != ""
}

// isTokenExpired checks if the provided OAuthToken is expired based on the expiry timestamp.
func (o OAuth2SandboxCredentials) isTokenExpired() bool {
    return *o.OAuthToken().Expiry <= int64(time.Now().Second())
}

// OAuth2SandboxManager is a manager responsible for handling authorization related operations.
type OAuth2SandboxManager struct {
    oAuth2SandboxCredentials     OAuth2SandboxCredentials
    oAuthAuthorizationController OAuthAuthorizationController
    oAuthToken                   models.OAuthToken
}

// newOAuth2SandboxManager creates a new instance of OAuth2SandboxManager with the given oAuth2SandboxCredentials and OAuthAuthorizationController.
func newOAuth2SandboxManager(
    oAuth2SandboxCredentials OAuth2SandboxCredentials,
    oAuthAuthorizationController OAuthAuthorizationController) *OAuth2SandboxManager {
    oAuth2SandboxManager := &OAuth2SandboxManager{
        oAuth2SandboxCredentials: oAuth2SandboxCredentials,
        oAuthAuthorizationController: oAuthAuthorizationController,
        oAuthToken: oAuth2SandboxCredentials.OAuthToken(),
    }
    
    return oAuth2SandboxManager
}

// Validate function returns validation error associated with the OAuth2SandboxManager.
func (o *OAuth2SandboxManager) Validate() error {
    if o.oAuth2SandboxCredentials.OAuthClientId() == "" || o.oAuth2SandboxCredentials.OAuthClientSecret() == "" {
        return errors.New("OAuth2-sandbox : missing auth credentials -> OAuthClientId && OAuthClientSecret")
    }
    
    if !o.OAuthTokenIsAuthorize() || o.OAuthTokenIsExpired() {
        tokenProvider := o.oAuth2SandboxCredentials.OAuthTokenProvider()
        if tokenProvider != nil {
            o.oAuthToken = tokenProvider(o.oAuth2SandboxCredentials.OAuthToken(), *o)
        } else if token, err := o.FetchToken(context.TODO()); err == nil {
            o.oAuthToken = token
        }
    
        onTokenUpdate := o.oAuth2SandboxCredentials.OAuthOnTokenUpdate()
        if onTokenUpdate != nil {
            onTokenUpdate(o.oAuthToken)
        }
    }
    
    if !o.OAuthTokenIsAuthorize() {
    return errors.New("OAuth2-sandbox : Client is not authorized. An OAuth token is needed to make API calls")
}
     if o.OAuthTokenIsExpired() {
    return errors.New("OAuth2-sandbox : OAuth token is expired. A valid token is needed to make API calls")
}
    return nil
}

// Authenticator function returns HttpInterceptor function that provides authentication for API calls.
func (o *OAuth2SandboxManager) Authenticator() https.HttpInterceptor {
    return func(req *http.Request,
        next https.HttpCallExecutor,
    ) https.HttpContext {
            req.Header.Set(https.AUTHORIZATION_HEADER, "Bearer "+ o.oAuthToken.AccessToken)
        return next(req)
    }
}

// FetchToken fetches the token. It makes a request to the OAuthAuthorizationController
// to obtain the token and returns the token and any error occurred during the request.
func (o *OAuth2SandboxManager) FetchToken(ctx context.Context) (
    models.OAuthToken,
    error) {
    authorization := o.getEncodedString()
    scope := o.getStringScopes()
    result, err := o.oAuthAuthorizationController.RequestTokenOAuth2Sandbox(ctx, authorization, &scope, nil)
    if result.Data.ExpiresIn != nil && *result.Data.ExpiresIn != 0 {
        result.Data.Expiry = models.ToPointer(int64(time.Now().Second() + int(*result.Data.ExpiresIn)))
    }
    
    return result.Data, err
}

// getEncodedString encodes the provided credentials (OAuthClientId and OAuthClientSecret) to a Basic Auth string.
func (o *OAuth2SandboxManager) getEncodedString() string {
    return "Basic " + base64.StdEncoding.EncodeToString([]byte(o.oAuth2SandboxCredentials.OAuthClientId() + ":" + o.oAuth2SandboxCredentials.OAuthClientSecret()))
}

// getStringScopes concatenate the provided slice of oAuthScopes Enum to string.
func (o *OAuth2SandboxManager) getStringScopes() string {
    var oAuthScopes string
    for i, scope := range o.oAuth2SandboxCredentials.OAuthScopes() {
        if i == 0 {
            oAuthScopes = string(scope)
        } else {
            oAuthScopes = oAuthScopes + " " + string(scope)
        }
    }
    return oAuthScopes
}

// OAuthTokenIsAuthorize checks the expiry of OAuth Token.
func (o *OAuth2SandboxManager) OAuthTokenIsAuthorize() bool {
    return o.oAuthToken.AccessToken != ""
}

// OAuthTokenIsExpired checks the expiry of OAuth Token.
func (o *OAuth2SandboxManager) OAuthTokenIsExpired() bool {
    return *o.oAuthToken.Expiry <= int64(time.Now().Second()) + o.oAuth2SandboxCredentials.OAuthClockSkew()
}
