// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

import (
    "context"
    "encoding/base64"
    "errors"
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
    "splititwebapiv3/models"
    "time"
)

// OAuth2ProductionCredentials represents the credentials required for `OAuth2-production` authentication.
type OAuth2ProductionCredentials struct {
    oAuthClientId      string
    oAuthClientSecret  string
    oAuthToken         models.OAuthToken
    oAuthScopes        []models.OAuthScopeOAuth2ProductionEnum
    oAuthTokenProvider func (models.OAuthToken, OAuth2ProductionManager) models.OAuthToken
    oAuthOnTokenUpdate func (token models.OAuthToken)
    oAuthClockSkew     int64
}

// NewOAuth2ProductionCredentials creates a new instance of OAuth2ProductionCredentials with provided parameters.
func NewOAuth2ProductionCredentials(
    oAuthClientId string,
    oAuthClientSecret string) OAuth2ProductionCredentials {
    return OAuth2ProductionCredentials {
        oAuthClientId: oAuthClientId,
        oAuthClientSecret: oAuthClientSecret,
        oAuthClockSkew: 0,
    }
}

// WithOAuthClientId sets oAuthClientId in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthClientId(oAuthClientId string) OAuth2ProductionCredentials {
    o.oAuthClientId = oAuthClientId
    return o
}

// WithOAuthClientSecret sets oAuthClientSecret in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthClientSecret(oAuthClientSecret string) OAuth2ProductionCredentials {
    o.oAuthClientSecret = oAuthClientSecret
    return o
}

// WithOAuthToken sets oAuthToken in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthToken(oAuthToken models.OAuthToken) OAuth2ProductionCredentials {
    o.oAuthToken = oAuthToken
    return o
}

// WithOAuthScopes sets oAuthScopes in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthScopes(oAuthScopes []models.OAuthScopeOAuth2ProductionEnum) OAuth2ProductionCredentials {
    o.oAuthScopes = oAuthScopes
    return o
}

// WithOAuthTokenProvider sets oAuthTokenProvider in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthTokenProvider(oAuthTokenProvider func (models.OAuthToken, OAuth2ProductionManager) models.OAuthToken) OAuth2ProductionCredentials {
    o.oAuthTokenProvider = oAuthTokenProvider
    return o
}

// WithOAuthOnTokenUpdate sets oAuthOnTokenUpdate in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthOnTokenUpdate(oAuthOnTokenUpdate func (token models.OAuthToken)) OAuth2ProductionCredentials {
    o.oAuthOnTokenUpdate = oAuthOnTokenUpdate
    return o
}

// WithOAuthClockSkew sets oAuthClockSkew in OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) WithOAuthClockSkew(oAuthClockSkew int64) OAuth2ProductionCredentials {
    o.oAuthClockSkew = oAuthClockSkew
    return o
}

// OAuthClientId returns the oAuthClientId associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthClientId() string {
    return o.oAuthClientId
}

// OAuthClientSecret returns the oAuthClientSecret associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthClientSecret() string {
    return o.oAuthClientSecret
}

// OAuthToken returns the oAuthToken associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthToken() models.OAuthToken {
    return o.oAuthToken
}

// OAuthScopes returns the oAuthScopes associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthScopes() []models.OAuthScopeOAuth2ProductionEnum {
    return o.oAuthScopes
}

// OAuthTokenProvider returns the oAuthTokenProvider associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthTokenProvider() func (models.OAuthToken, OAuth2ProductionManager) models.OAuthToken {
    return o.oAuthTokenProvider
}

// OAuthOnTokenUpdate returns the oAuthOnTokenUpdate associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthOnTokenUpdate() func (token models.OAuthToken) {
    return o.oAuthOnTokenUpdate
}

// OAuthClockSkew returns the oAuthClockSkew associated with the OAuth2ProductionCredentials.
func (o OAuth2ProductionCredentials) OAuthClockSkew() int64 {
    return o.oAuthClockSkew
}

// isTokenValid checks if the provided OAuthToken is valid.
func (o OAuth2ProductionCredentials) isTokenValid() bool {
    return o.OAuthToken().AccessToken != ""
}

// isTokenExpired checks if the provided OAuthToken is expired based on the expiry timestamp.
func (o OAuth2ProductionCredentials) isTokenExpired() bool {
    return *o.OAuthToken().Expiry <= int64(time.Now().Second())
}

// OAuth2ProductionManager is a manager responsible for handling authorization related operations.
type OAuth2ProductionManager struct {
    oAuth2ProductionCredentials  OAuth2ProductionCredentials
    oAuthAuthorizationController OAuthAuthorizationController
    oAuthToken                   models.OAuthToken
}

// newOAuth2ProductionManager creates a new instance of OAuth2ProductionManager with the given oAuth2ProductionCredentials and OAuthAuthorizationController.
func newOAuth2ProductionManager(
    oAuth2ProductionCredentials OAuth2ProductionCredentials,
    oAuthAuthorizationController OAuthAuthorizationController) *OAuth2ProductionManager {
    oAuth2ProductionManager := &OAuth2ProductionManager{
        oAuth2ProductionCredentials: oAuth2ProductionCredentials,
        oAuthAuthorizationController: oAuthAuthorizationController,
        oAuthToken: oAuth2ProductionCredentials.OAuthToken(),
    }
    
    return oAuth2ProductionManager
}

// Validate function returns validation error associated with the OAuth2ProductionManager.
func (o *OAuth2ProductionManager) Validate() error {
    if o.oAuth2ProductionCredentials.OAuthClientId() == "" || o.oAuth2ProductionCredentials.OAuthClientSecret() == "" {
        return errors.New("OAuth2-production : missing auth credentials -> OAuthClientId && OAuthClientSecret")
    }
    
    if !o.OAuthTokenIsAuthorize() || o.OAuthTokenIsExpired() {
        tokenProvider := o.oAuth2ProductionCredentials.OAuthTokenProvider()
        if tokenProvider != nil {
            o.oAuthToken = tokenProvider(o.oAuth2ProductionCredentials.OAuthToken(), *o)
        } else if token, err := o.FetchToken(context.TODO()); err == nil {
            o.oAuthToken = token
        }
    
        onTokenUpdate := o.oAuth2ProductionCredentials.OAuthOnTokenUpdate()
        if onTokenUpdate != nil {
            onTokenUpdate(o.oAuthToken)
        }
    }
    
    if !o.OAuthTokenIsAuthorize() {
    return errors.New("OAuth2-production : Client is not authorized. An OAuth token is needed to make API calls")
}
     if o.OAuthTokenIsExpired() {
    return errors.New("OAuth2-production : OAuth token is expired. A valid token is needed to make API calls")
}
    return nil
}

// Authenticator function returns HttpInterceptor function that provides authentication for API calls.
func (o *OAuth2ProductionManager) Authenticator() https.HttpInterceptor {
    return func(req *http.Request,
        next https.HttpCallExecutor,
    ) https.HttpContext {
            req.Header.Set(https.AUTHORIZATION_HEADER, "Bearer "+ o.oAuthToken.AccessToken)
        return next(req)
    }
}

// FetchToken fetches the token. It makes a request to the OAuthAuthorizationController
// to obtain the token and returns the token and any error occurred during the request.
func (o *OAuth2ProductionManager) FetchToken(ctx context.Context) (
    models.OAuthToken,
    error) {
    authorization := o.getEncodedString()
    scope := o.getStringScopes()
    result, err := o.oAuthAuthorizationController.RequestTokenOAuth2Production(ctx, authorization, &scope, nil)
    if result.Data.ExpiresIn != nil && *result.Data.ExpiresIn != 0 {
        result.Data.Expiry = models.ToPointer(int64(time.Now().Second() + int(*result.Data.ExpiresIn)))
    }
    
    return result.Data, err
}

// getEncodedString encodes the provided credentials (OAuthClientId and OAuthClientSecret) to a Basic Auth string.
func (o *OAuth2ProductionManager) getEncodedString() string {
    return "Basic " + base64.StdEncoding.EncodeToString([]byte(o.oAuth2ProductionCredentials.OAuthClientId() + ":" + o.oAuth2ProductionCredentials.OAuthClientSecret()))
}

// getStringScopes concatenate the provided slice of oAuthScopes Enum to string.
func (o *OAuth2ProductionManager) getStringScopes() string {
    var oAuthScopes string
    for i, scope := range o.oAuth2ProductionCredentials.OAuthScopes() {
        if i == 0 {
            oAuthScopes = string(scope)
        } else {
            oAuthScopes = oAuthScopes + " " + string(scope)
        }
    }
    return oAuthScopes
}

// OAuthTokenIsAuthorize checks the expiry of OAuth Token.
func (o *OAuth2ProductionManager) OAuthTokenIsAuthorize() bool {
    return o.oAuthToken.AccessToken != ""
}

// OAuthTokenIsExpired checks the expiry of OAuth Token.
func (o *OAuth2ProductionManager) OAuthTokenIsExpired() bool {
    return *o.oAuthToken.Expiry <= int64(time.Now().Second()) + o.oAuth2ProductionCredentials.OAuthClockSkew()
}
