// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package splititwebapiv3

var installmentPlanController InstallmentPlanController

// init is an initialization function that sets up the controllers.
// It creates a configuration from the environment with a specified HTTP configuration and initializes the client.
// Then, it assigns the different controllers from the client to the corresponding variables for further use.
func init() {
    
    config := CreateConfigurationFromEnvironment(
        WithHttpConfiguration(
            CreateHttpConfiguration(
                WithTimeout(30),
            ),
        ),
    )
    
    client := NewClient(config)
    
    installmentPlanController = *client.InstallmentPlanController()
}
