// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package errors

import (
    "fmt"
    "github.com/apimatic/go-core-runtime/https"
    "splititwebapiv3/models"
    "strings"
)

// FailedResponse is a custom error.
type FailedResponse struct {
    https.ApiError
    TraceId        *string               `json:"TraceId,omitempty"`
    MError         *models.ErrorExtended `json:"Error,omitempty"`
}

// NewFailedResponse is a constructor for FailedResponse.
// It creates and returns a pointer to a new FailedResponse instance with the given statusCode and body.
func NewFailedResponse(apiError https.ApiError) error {
    return &FailedResponse{
		ApiError: apiError,
    }
}

// Error implements the Error method for the error interface.
// It returns a formatted error message for FailedResponse.
func (f FailedResponse) Error() string {
    return fmt.Sprintf("FailedResponse occured: %v", f.Message)
}

// String implements the fmt.Stringer interface for FailedResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (f FailedResponse) String() string {
    suffixTrimmed := strings.TrimSuffix(f.ApiError.String(), "]")
    prefixTrimmed := strings.TrimPrefix(suffixTrimmed, "ApiError[")
    
    return fmt.Sprintf(
    	"FailedResponse[%v, TraceId=%v, MError=%v]",
    	prefixTrimmed, f.TraceId, f.MError)
}

// PlanErrorResponse is a custom error.
type PlanErrorResponse struct {
    https.ApiError
    TraceId               *string               `json:"TraceId,omitempty"`
    MError                *models.ErrorExtended `json:"Error,omitempty"`
    InstallmentPlanNumber *string               `json:"InstallmentPlanNumber,omitempty"`
    PaymentInfo           *models.PaymentInfo   `json:"PaymentInfo,omitempty"`
}

// NewPlanErrorResponse is a constructor for PlanErrorResponse.
// It creates and returns a pointer to a new PlanErrorResponse instance with the given statusCode and body.
func NewPlanErrorResponse(apiError https.ApiError) error {
    return &PlanErrorResponse{
		ApiError: apiError,
    }
}

// Error implements the Error method for the error interface.
// It returns a formatted error message for PlanErrorResponse.
func (p PlanErrorResponse) Error() string {
    return fmt.Sprintf("PlanErrorResponse occured: %v", p.Message)
}

// String implements the fmt.Stringer interface for PlanErrorResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PlanErrorResponse) String() string {
    suffixTrimmed := strings.TrimSuffix(p.ApiError.String(), "]")
    prefixTrimmed := strings.TrimPrefix(suffixTrimmed, "ApiError[")
    
    return fmt.Sprintf(
    	"PlanErrorResponse[%v, TraceId=%v, MError=%v, InstallmentPlanNumber=%v, PaymentInfo=%v]",
    	prefixTrimmed, p.TraceId, p.MError, p.InstallmentPlanNumber, p.PaymentInfo)
}

// OAuthProvider is a custom error.
// OAuth 2 Authorization endpoint exception.
type OAuthProvider struct {
    https.ApiError
    MError           models.OAuthProviderErrorEnum `json:"error"`
    ErrorDescription *string                       `json:"error_description,omitempty"`
    ErrorUri         *string                       `json:"error_uri,omitempty"`
}

// NewOAuthProvider is a constructor for OAuthProvider.
// It creates and returns a pointer to a new OAuthProvider instance with the given statusCode and body.
func NewOAuthProvider(apiError https.ApiError) error {
    return &OAuthProvider{
		ApiError: apiError,
    }
}

// Error implements the Error method for the error interface.
// It returns a formatted error message for OAuthProvider.
func (o OAuthProvider) Error() string {
    return fmt.Sprintf("OAuthProvider occured: %v", o.Message)
}

// String implements the fmt.Stringer interface for OAuthProvider,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (o OAuthProvider) String() string {
    suffixTrimmed := strings.TrimSuffix(o.ApiError.String(), "]")
    prefixTrimmed := strings.TrimPrefix(suffixTrimmed, "ApiError[")
    
    return fmt.Sprintf(
    	"OAuthProvider[%v, MError=%v, ErrorDescription=%v, ErrorUri=%v]",
    	prefixTrimmed, o.MError, o.ErrorDescription, o.ErrorUri)
}
