// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// AddressDataModel represents a AddressDataModel struct.
type AddressDataModel struct {
    AddressLine1         *string                `json:"AddressLine1,omitempty"`
    AddressLine2         *string                `json:"AddressLine2,omitempty"`
    City                 *string                `json:"City,omitempty"`
    Country              *string                `json:"Country,omitempty"`
    State                *string                `json:"State,omitempty"`
    Zip                  *string                `json:"Zip,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for AddressDataModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AddressDataModel) String() string {
    return fmt.Sprintf(
    	"AddressDataModel[AddressLine1=%v, AddressLine2=%v, City=%v, Country=%v, State=%v, Zip=%v, AdditionalProperties=%v]",
    	a.AddressLine1, a.AddressLine2, a.City, a.Country, a.State, a.Zip, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AddressDataModel.
// It customizes the JSON marshaling process for AddressDataModel objects.
func (a AddressDataModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "AddressLine1", "AddressLine2", "City", "Country", "State", "Zip"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AddressDataModel object to a map representation for JSON marshaling.
func (a AddressDataModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    if a.AddressLine1 != nil {
        structMap["AddressLine1"] = a.AddressLine1
    }
    if a.AddressLine2 != nil {
        structMap["AddressLine2"] = a.AddressLine2
    }
    if a.City != nil {
        structMap["City"] = a.City
    }
    if a.Country != nil {
        structMap["Country"] = a.Country
    }
    if a.State != nil {
        structMap["State"] = a.State
    }
    if a.Zip != nil {
        structMap["Zip"] = a.Zip
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AddressDataModel.
// It customizes the JSON unmarshaling process for AddressDataModel objects.
func (a *AddressDataModel) UnmarshalJSON(input []byte) error {
    var temp tempAddressDataModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "AddressLine1", "AddressLine2", "City", "Country", "State", "Zip")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.AddressLine1 = temp.AddressLine1
    a.AddressLine2 = temp.AddressLine2
    a.City = temp.City
    a.Country = temp.Country
    a.State = temp.State
    a.Zip = temp.Zip
    return nil
}

// tempAddressDataModel is a temporary struct used for validating the fields of AddressDataModel.
type tempAddressDataModel  struct {
    AddressLine1 *string `json:"AddressLine1,omitempty"`
    AddressLine2 *string `json:"AddressLine2,omitempty"`
    City         *string `json:"City,omitempty"`
    Country      *string `json:"Country,omitempty"`
    State        *string `json:"State,omitempty"`
    Zip          *string `json:"Zip,omitempty"`
}
