// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// AuthorizationModel represents a AuthorizationModel struct.
type AuthorizationModel struct {
    Status                 GwAuthorizationStatusEnum `json:"Status"`
    Date                   *time.Time                `json:"Date,omitempty"`
    SplititErrorResultCode *string                   `json:"SplititErrorResultCode,omitempty"`
    GatewayTransactionID   *string                   `json:"GatewayTransactionID,omitempty"`
    GatewayResultCode      *string                   `json:"GatewayResultCode,omitempty"`
    GatewayResultMessage   *string                   `json:"GatewayResultMessage,omitempty"`
    ThreeDSRedirect        *ThreeDsRedirectDataV3    `json:"ThreeDSRedirect,omitempty"`
    CAVV                   *string                   `json:"CAVV,omitempty"`
    ECI                    *string                   `json:"ECI,omitempty"`
    GatewaySourceResponse  *string                   `json:"GatewaySourceResponse,omitempty"`
    AdditionalProperties   map[string]interface{}    `json:"_"`
}

// String implements the fmt.Stringer interface for AuthorizationModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AuthorizationModel) String() string {
    return fmt.Sprintf(
    	"AuthorizationModel[Status=%v, Date=%v, SplititErrorResultCode=%v, GatewayTransactionID=%v, GatewayResultCode=%v, GatewayResultMessage=%v, ThreeDSRedirect=%v, CAVV=%v, ECI=%v, GatewaySourceResponse=%v, AdditionalProperties=%v]",
    	a.Status, a.Date, a.SplititErrorResultCode, a.GatewayTransactionID, a.GatewayResultCode, a.GatewayResultMessage, a.ThreeDSRedirect, a.CAVV, a.ECI, a.GatewaySourceResponse, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AuthorizationModel.
// It customizes the JSON marshaling process for AuthorizationModel objects.
func (a AuthorizationModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "Status", "Date", "SplititErrorResultCode", "GatewayTransactionID", "GatewayResultCode", "GatewayResultMessage", "ThreeDSRedirect", "CAVV", "ECI", "GatewaySourceResponse"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AuthorizationModel object to a map representation for JSON marshaling.
func (a AuthorizationModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    structMap["Status"] = a.Status
    if a.Date != nil {
        structMap["Date"] = a.Date.Format(time.RFC3339)
    }
    if a.SplititErrorResultCode != nil {
        structMap["SplititErrorResultCode"] = a.SplititErrorResultCode
    }
    if a.GatewayTransactionID != nil {
        structMap["GatewayTransactionID"] = a.GatewayTransactionID
    }
    if a.GatewayResultCode != nil {
        structMap["GatewayResultCode"] = a.GatewayResultCode
    }
    if a.GatewayResultMessage != nil {
        structMap["GatewayResultMessage"] = a.GatewayResultMessage
    }
    if a.ThreeDSRedirect != nil {
        structMap["ThreeDSRedirect"] = a.ThreeDSRedirect.toMap()
    }
    if a.CAVV != nil {
        structMap["CAVV"] = a.CAVV
    }
    if a.ECI != nil {
        structMap["ECI"] = a.ECI
    }
    if a.GatewaySourceResponse != nil {
        structMap["GatewaySourceResponse"] = a.GatewaySourceResponse
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AuthorizationModel.
// It customizes the JSON unmarshaling process for AuthorizationModel objects.
func (a *AuthorizationModel) UnmarshalJSON(input []byte) error {
    var temp tempAuthorizationModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Status", "Date", "SplititErrorResultCode", "GatewayTransactionID", "GatewayResultCode", "GatewayResultMessage", "ThreeDSRedirect", "CAVV", "ECI", "GatewaySourceResponse")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.Status = *temp.Status
    if temp.Date != nil {
        DateVal, err := time.Parse(time.RFC3339, *temp.Date)
        if err != nil {
            log.Fatalf("Cannot Parse Date as % s format.", time.RFC3339)
        }
        a.Date = &DateVal
    }
    a.SplititErrorResultCode = temp.SplititErrorResultCode
    a.GatewayTransactionID = temp.GatewayTransactionID
    a.GatewayResultCode = temp.GatewayResultCode
    a.GatewayResultMessage = temp.GatewayResultMessage
    a.ThreeDSRedirect = temp.ThreeDSRedirect
    a.CAVV = temp.CAVV
    a.ECI = temp.ECI
    a.GatewaySourceResponse = temp.GatewaySourceResponse
    return nil
}

// tempAuthorizationModel is a temporary struct used for validating the fields of AuthorizationModel.
type tempAuthorizationModel  struct {
    Status                 *GwAuthorizationStatusEnum `json:"Status"`
    Date                   *string                    `json:"Date,omitempty"`
    SplititErrorResultCode *string                    `json:"SplititErrorResultCode,omitempty"`
    GatewayTransactionID   *string                    `json:"GatewayTransactionID,omitempty"`
    GatewayResultCode      *string                    `json:"GatewayResultCode,omitempty"`
    GatewayResultMessage   *string                    `json:"GatewayResultMessage,omitempty"`
    ThreeDSRedirect        *ThreeDsRedirectDataV3     `json:"ThreeDSRedirect,omitempty"`
    CAVV                   *string                    `json:"CAVV,omitempty"`
    ECI                    *string                    `json:"ECI,omitempty"`
    GatewaySourceResponse  *string                    `json:"GatewaySourceResponse,omitempty"`
}

func (a *tempAuthorizationModel) validate() error {
    var errs []string
    if a.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `AuthorizationModel`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
