// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// BluesnapVaultedShopperToken represents a BluesnapVaultedShopperToken struct.
type BluesnapVaultedShopperToken struct {
    Token                *string                `json:"Token,omitempty"`
    Last4Digit           *string                `json:"Last4Digit,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for BluesnapVaultedShopperToken,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (b BluesnapVaultedShopperToken) String() string {
    return fmt.Sprintf(
    	"BluesnapVaultedShopperToken[Token=%v, Last4Digit=%v, AdditionalProperties=%v]",
    	b.Token, b.Last4Digit, b.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for BluesnapVaultedShopperToken.
// It customizes the JSON marshaling process for BluesnapVaultedShopperToken objects.
func (b BluesnapVaultedShopperToken) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(b.AdditionalProperties,
        "Token", "Last4Digit"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(b.toMap())
}

// toMap converts the BluesnapVaultedShopperToken object to a map representation for JSON marshaling.
func (b BluesnapVaultedShopperToken) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, b.AdditionalProperties)
    if b.Token != nil {
        structMap["Token"] = b.Token
    }
    if b.Last4Digit != nil {
        structMap["Last4Digit"] = b.Last4Digit
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for BluesnapVaultedShopperToken.
// It customizes the JSON unmarshaling process for BluesnapVaultedShopperToken objects.
func (b *BluesnapVaultedShopperToken) UnmarshalJSON(input []byte) error {
    var temp tempBluesnapVaultedShopperToken
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Token", "Last4Digit")
    if err != nil {
    	return err
    }
    b.AdditionalProperties = additionalProperties
    
    b.Token = temp.Token
    b.Last4Digit = temp.Last4Digit
    return nil
}

// tempBluesnapVaultedShopperToken is a temporary struct used for validating the fields of BluesnapVaultedShopperToken.
type tempBluesnapVaultedShopperToken  struct {
    Token      *string `json:"Token,omitempty"`
    Last4Digit *string `json:"Last4Digit,omitempty"`
}
