// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// CardData represents a CardData struct.
type CardData struct {
    CardHolderFullName   *string                `json:"CardHolderFullName,omitempty"`
    CardNumber           *string                `json:"CardNumber,omitempty"`
    CardExpYear          *string                `json:"CardExpYear,omitempty"`
    CardExpMonth         *string                `json:"CardExpMonth,omitempty"`
    CardCvv              *string                `json:"CardCvv,omitempty"`
    CardBrand            *CardBrandEnum         `json:"CardBrand,omitempty"`
    CardType             *CardTypeEnum          `json:"CardType,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CardData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CardData) String() string {
    return fmt.Sprintf(
    	"CardData[CardHolderFullName=%v, CardNumber=%v, CardExpYear=%v, CardExpMonth=%v, CardCvv=%v, CardBrand=%v, CardType=%v, AdditionalProperties=%v]",
    	c.CardHolderFullName, c.CardNumber, c.CardExpYear, c.CardExpMonth, c.CardCvv, c.CardBrand, c.CardType, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CardData.
// It customizes the JSON marshaling process for CardData objects.
func (c CardData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "CardHolderFullName", "CardNumber", "CardExpYear", "CardExpMonth", "CardCvv", "CardBrand", "CardType"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CardData object to a map representation for JSON marshaling.
func (c CardData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.CardHolderFullName != nil {
        structMap["CardHolderFullName"] = c.CardHolderFullName
    }
    if c.CardNumber != nil {
        structMap["CardNumber"] = c.CardNumber
    }
    if c.CardExpYear != nil {
        structMap["CardExpYear"] = c.CardExpYear
    }
    if c.CardExpMonth != nil {
        structMap["CardExpMonth"] = c.CardExpMonth
    }
    if c.CardCvv != nil {
        structMap["CardCvv"] = c.CardCvv
    }
    if c.CardBrand != nil {
        structMap["CardBrand"] = c.CardBrand
    }
    if c.CardType != nil {
        structMap["CardType"] = c.CardType
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CardData.
// It customizes the JSON unmarshaling process for CardData objects.
func (c *CardData) UnmarshalJSON(input []byte) error {
    var temp tempCardData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "CardHolderFullName", "CardNumber", "CardExpYear", "CardExpMonth", "CardCvv", "CardBrand", "CardType")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.CardHolderFullName = temp.CardHolderFullName
    c.CardNumber = temp.CardNumber
    c.CardExpYear = temp.CardExpYear
    c.CardExpMonth = temp.CardExpMonth
    c.CardCvv = temp.CardCvv
    c.CardBrand = temp.CardBrand
    c.CardType = temp.CardType
    return nil
}

// tempCardData is a temporary struct used for validating the fields of CardData.
type tempCardData  struct {
    CardHolderFullName *string        `json:"CardHolderFullName,omitempty"`
    CardNumber         *string        `json:"CardNumber,omitempty"`
    CardExpYear        *string        `json:"CardExpYear,omitempty"`
    CardExpMonth       *string        `json:"CardExpMonth,omitempty"`
    CardCvv            *string        `json:"CardCvv,omitempty"`
    CardBrand          *CardBrandEnum `json:"CardBrand,omitempty"`
    CardType           *CardTypeEnum  `json:"CardType,omitempty"`
}
