// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// CheckInstallmentsEligibilityRequest represents a CheckInstallmentsEligibilityRequest struct.
type CheckInstallmentsEligibilityRequest struct {
    PlanData             *PlanData              `json:"PlanData,omitempty"`
    CardDetails          *CardData              `json:"CardDetails,omitempty"`
    BillingAddress       *AddressData           `json:"BillingAddress,omitempty"`
    ShopperIdentifier    *string                `json:"ShopperIdentifier,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CheckInstallmentsEligibilityRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CheckInstallmentsEligibilityRequest) String() string {
    return fmt.Sprintf(
    	"CheckInstallmentsEligibilityRequest[PlanData=%v, CardDetails=%v, BillingAddress=%v, ShopperIdentifier=%v, AdditionalProperties=%v]",
    	c.PlanData, c.CardDetails, c.BillingAddress, c.ShopperIdentifier, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CheckInstallmentsEligibilityRequest.
// It customizes the JSON marshaling process for CheckInstallmentsEligibilityRequest objects.
func (c CheckInstallmentsEligibilityRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "PlanData", "CardDetails", "BillingAddress", "ShopperIdentifier"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CheckInstallmentsEligibilityRequest object to a map representation for JSON marshaling.
func (c CheckInstallmentsEligibilityRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.PlanData != nil {
        structMap["PlanData"] = c.PlanData.toMap()
    }
    if c.CardDetails != nil {
        structMap["CardDetails"] = c.CardDetails.toMap()
    }
    if c.BillingAddress != nil {
        structMap["BillingAddress"] = c.BillingAddress.toMap()
    }
    if c.ShopperIdentifier != nil {
        structMap["ShopperIdentifier"] = c.ShopperIdentifier
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CheckInstallmentsEligibilityRequest.
// It customizes the JSON unmarshaling process for CheckInstallmentsEligibilityRequest objects.
func (c *CheckInstallmentsEligibilityRequest) UnmarshalJSON(input []byte) error {
    var temp tempCheckInstallmentsEligibilityRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "PlanData", "CardDetails", "BillingAddress", "ShopperIdentifier")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.PlanData = temp.PlanData
    c.CardDetails = temp.CardDetails
    c.BillingAddress = temp.BillingAddress
    c.ShopperIdentifier = temp.ShopperIdentifier
    return nil
}

// tempCheckInstallmentsEligibilityRequest is a temporary struct used for validating the fields of CheckInstallmentsEligibilityRequest.
type tempCheckInstallmentsEligibilityRequest  struct {
    PlanData          *PlanData    `json:"PlanData,omitempty"`
    CardDetails       *CardData    `json:"CardDetails,omitempty"`
    BillingAddress    *AddressData `json:"BillingAddress,omitempty"`
    ShopperIdentifier *string      `json:"ShopperIdentifier,omitempty"`
}
