// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// EligibilityTermsAndConditionResponse represents a EligibilityTermsAndConditionResponse struct.
type EligibilityTermsAndConditionResponse struct {
    TermsAndConditions   *string                `json:"TermsAndConditions,omitempty"`
    PrivacyPolicy        *string                `json:"PrivacyPolicy,omitempty"`
    Provider             *string                `json:"Provider,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EligibilityTermsAndConditionResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EligibilityTermsAndConditionResponse) String() string {
    return fmt.Sprintf(
    	"EligibilityTermsAndConditionResponse[TermsAndConditions=%v, PrivacyPolicy=%v, Provider=%v, AdditionalProperties=%v]",
    	e.TermsAndConditions, e.PrivacyPolicy, e.Provider, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EligibilityTermsAndConditionResponse.
// It customizes the JSON marshaling process for EligibilityTermsAndConditionResponse objects.
func (e EligibilityTermsAndConditionResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "TermsAndConditions", "PrivacyPolicy", "Provider"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EligibilityTermsAndConditionResponse object to a map representation for JSON marshaling.
func (e EligibilityTermsAndConditionResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.TermsAndConditions != nil {
        structMap["TermsAndConditions"] = e.TermsAndConditions
    }
    if e.PrivacyPolicy != nil {
        structMap["PrivacyPolicy"] = e.PrivacyPolicy
    }
    if e.Provider != nil {
        structMap["Provider"] = e.Provider
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EligibilityTermsAndConditionResponse.
// It customizes the JSON unmarshaling process for EligibilityTermsAndConditionResponse objects.
func (e *EligibilityTermsAndConditionResponse) UnmarshalJSON(input []byte) error {
    var temp tempEligibilityTermsAndConditionResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "TermsAndConditions", "PrivacyPolicy", "Provider")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.TermsAndConditions = temp.TermsAndConditions
    e.PrivacyPolicy = temp.PrivacyPolicy
    e.Provider = temp.Provider
    return nil
}

// tempEligibilityTermsAndConditionResponse is a temporary struct used for validating the fields of EligibilityTermsAndConditionResponse.
type tempEligibilityTermsAndConditionResponse  struct {
    TermsAndConditions *string `json:"TermsAndConditions,omitempty"`
    PrivacyPolicy      *string `json:"PrivacyPolicy,omitempty"`
    Provider           *string `json:"Provider,omitempty"`
}
