// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// CardBrandEnum is a string enum.
type CardBrandEnum string

// MarshalJSON implements the json.Marshaler interface for CardBrandEnum.
// It customizes the JSON marshaling process for CardBrandEnum objects.
func (e CardBrandEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for CardBrandEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for CardBrandEnum.
// It customizes the JSON unmarshaling process for CardBrandEnum objects.
func (e *CardBrandEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = CardBrandEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to CardBrandEnum")
    }
    return nil
}

// Checks whether the value is actually a member of CardBrandEnum.
func (e CardBrandEnum) isValid() bool {
    switch e {
    case CardBrandEnum_MASTERCARD,
        CardBrandEnum_VISA,
        CardBrandEnum_AMERICANEXPRESS,
        CardBrandEnum_MAESTRO,
        CardBrandEnum_JCB,
        CardBrandEnum_CUP,
        CardBrandEnum_UPI,
        CardBrandEnum_DISCOVER,
        CardBrandEnum_OTHER:
        return true
    }
    return false
}

const (
    CardBrandEnum_MASTERCARD      CardBrandEnum = "Mastercard"
    CardBrandEnum_VISA            CardBrandEnum = "Visa"
    CardBrandEnum_AMERICANEXPRESS CardBrandEnum = "AmericanExpress"
    CardBrandEnum_MAESTRO         CardBrandEnum = "Maestro"
    CardBrandEnum_JCB             CardBrandEnum = "JCB"
    CardBrandEnum_CUP             CardBrandEnum = "CUP"
    CardBrandEnum_UPI             CardBrandEnum = "UPI"
    CardBrandEnum_DISCOVER        CardBrandEnum = "Discover"
    CardBrandEnum_OTHER           CardBrandEnum = "Other"
)

// GwAuthorizationStatusEnum is a string enum.
type GwAuthorizationStatusEnum string

// MarshalJSON implements the json.Marshaler interface for GwAuthorizationStatusEnum.
// It customizes the JSON marshaling process for GwAuthorizationStatusEnum objects.
func (e GwAuthorizationStatusEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for GwAuthorizationStatusEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for GwAuthorizationStatusEnum.
// It customizes the JSON unmarshaling process for GwAuthorizationStatusEnum objects.
func (e *GwAuthorizationStatusEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = GwAuthorizationStatusEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to GwAuthorizationStatusEnum")
    }
    return nil
}

// Checks whether the value is actually a member of GwAuthorizationStatusEnum.
func (e GwAuthorizationStatusEnum) isValid() bool {
    switch e {
    case GwAuthorizationStatusEnum_NA,
        GwAuthorizationStatusEnum_SUCCEEDED,
        GwAuthorizationStatusEnum_PENDING3DS,
        GwAuthorizationStatusEnum_FAILED,
        GwAuthorizationStatusEnum_CANCELED,
        GwAuthorizationStatusEnum_VOIDED:
        return true
    }
    return false
}

const (
    GwAuthorizationStatusEnum_NA         GwAuthorizationStatusEnum = "NA"
    GwAuthorizationStatusEnum_SUCCEEDED  GwAuthorizationStatusEnum = "Succeeded"
    GwAuthorizationStatusEnum_PENDING3DS GwAuthorizationStatusEnum = "Pending3DS"
    GwAuthorizationStatusEnum_FAILED     GwAuthorizationStatusEnum = "Failed"
    GwAuthorizationStatusEnum_CANCELED   GwAuthorizationStatusEnum = "Canceled"
    GwAuthorizationStatusEnum_VOIDED     GwAuthorizationStatusEnum = "Voided"
)

// RefundStatusEnum is a string enum.
type RefundStatusEnum string

// MarshalJSON implements the json.Marshaler interface for RefundStatusEnum.
// It customizes the JSON marshaling process for RefundStatusEnum objects.
func (e RefundStatusEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for RefundStatusEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for RefundStatusEnum.
// It customizes the JSON unmarshaling process for RefundStatusEnum objects.
func (e *RefundStatusEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = RefundStatusEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to RefundStatusEnum")
    }
    return nil
}

// Checks whether the value is actually a member of RefundStatusEnum.
func (e RefundStatusEnum) isValid() bool {
    switch e {
    case RefundStatusEnum_PENDING,
        RefundStatusEnum_SUCCEEDED,
        RefundStatusEnum_FAILED:
        return true
    }
    return false
}

const (
    RefundStatusEnum_PENDING   RefundStatusEnum = "Pending"
    RefundStatusEnum_SUCCEEDED RefundStatusEnum = "Succeeded"
    RefundStatusEnum_FAILED    RefundStatusEnum = "Failed"
)

// TestModesEnum is a string enum.
type TestModesEnum string

// MarshalJSON implements the json.Marshaler interface for TestModesEnum.
// It customizes the JSON marshaling process for TestModesEnum objects.
func (e TestModesEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for TestModesEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestModesEnum.
// It customizes the JSON unmarshaling process for TestModesEnum objects.
func (e *TestModesEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = TestModesEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to TestModesEnum")
    }
    return nil
}

// Checks whether the value is actually a member of TestModesEnum.
func (e TestModesEnum) isValid() bool {
    switch e {
    case TestModesEnum_NONE,
        TestModesEnum_REGULAR,
        TestModesEnum_FAST,
        TestModesEnum_AUTOMATION:
        return true
    }
    return false
}

const (
    TestModesEnum_NONE       TestModesEnum = "None"
    TestModesEnum_REGULAR    TestModesEnum = "Regular"
    TestModesEnum_FAST       TestModesEnum = "Fast"
    TestModesEnum_AUTOMATION TestModesEnum = "Automation"
)

// ShippingStatusEnum is a string enum.
type ShippingStatusEnum string

// MarshalJSON implements the json.Marshaler interface for ShippingStatusEnum.
// It customizes the JSON marshaling process for ShippingStatusEnum objects.
func (e ShippingStatusEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for ShippingStatusEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShippingStatusEnum.
// It customizes the JSON unmarshaling process for ShippingStatusEnum objects.
func (e *ShippingStatusEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = ShippingStatusEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to ShippingStatusEnum")
    }
    return nil
}

// Checks whether the value is actually a member of ShippingStatusEnum.
func (e ShippingStatusEnum) isValid() bool {
    switch e {
    case ShippingStatusEnum_PENDING,
        ShippingStatusEnum_SHIPPED,
        ShippingStatusEnum_DELIVERED:
        return true
    }
    return false
}

const (
    ShippingStatusEnum_PENDING   ShippingStatusEnum = "Pending"
    ShippingStatusEnum_SHIPPED   ShippingStatusEnum = "Shipped"
    ShippingStatusEnum_DELIVERED ShippingStatusEnum = "Delivered"
)

// PlanStatusEnum is a string enum.
type PlanStatusEnum string

// MarshalJSON implements the json.Marshaler interface for PlanStatusEnum.
// It customizes the JSON marshaling process for PlanStatusEnum objects.
func (e PlanStatusEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for PlanStatusEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for PlanStatusEnum.
// It customizes the JSON unmarshaling process for PlanStatusEnum objects.
func (e *PlanStatusEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = PlanStatusEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to PlanStatusEnum")
    }
    return nil
}

// Checks whether the value is actually a member of PlanStatusEnum.
func (e PlanStatusEnum) isValid() bool {
    switch e {
    case PlanStatusEnum_INITIALIZED,
        PlanStatusEnum_PENDINGCAPTURE,
        PlanStatusEnum_ACTIVE,
        PlanStatusEnum_CLEARED,
        PlanStatusEnum_CANCELED:
        return true
    }
    return false
}

const (
    PlanStatusEnum_INITIALIZED    PlanStatusEnum = "Initialized"
    PlanStatusEnum_PENDINGCAPTURE PlanStatusEnum = "PendingCapture"
    PlanStatusEnum_ACTIVE         PlanStatusEnum = "Active"
    PlanStatusEnum_CLEARED        PlanStatusEnum = "Cleared"
    PlanStatusEnum_CANCELED       PlanStatusEnum = "Canceled"
)

// PaymentMethodTypeEnum is a string enum.
type PaymentMethodTypeEnum string

// MarshalJSON implements the json.Marshaler interface for PaymentMethodTypeEnum.
// It customizes the JSON marshaling process for PaymentMethodTypeEnum objects.
func (e PaymentMethodTypeEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for PaymentMethodTypeEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for PaymentMethodTypeEnum.
// It customizes the JSON unmarshaling process for PaymentMethodTypeEnum objects.
func (e *PaymentMethodTypeEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = PaymentMethodTypeEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to PaymentMethodTypeEnum")
    }
    return nil
}

// Checks whether the value is actually a member of PaymentMethodTypeEnum.
func (e PaymentMethodTypeEnum) isValid() bool {
    switch e {
    case PaymentMethodTypeEnum_CARD,
        PaymentMethodTypeEnum_SPLITITTOKEN,
        PaymentMethodTypeEnum_BLUESNAPVAULTEDSHOPPERTOKEN,
        PaymentMethodTypeEnum_SPLITITMOCKERV2TOKEN,
        PaymentMethodTypeEnum_SPREEDLYTOKEN:
        return true
    }
    return false
}

const (
    PaymentMethodTypeEnum_CARD                        PaymentMethodTypeEnum = "Card"
    PaymentMethodTypeEnum_SPLITITTOKEN                PaymentMethodTypeEnum = "SplititToken"
    PaymentMethodTypeEnum_BLUESNAPVAULTEDSHOPPERTOKEN PaymentMethodTypeEnum = "BluesnapVaultedShopperToken"
    PaymentMethodTypeEnum_SPLITITMOCKERV2TOKEN        PaymentMethodTypeEnum = "SplititMockerV2Token"
    PaymentMethodTypeEnum_SPREEDLYTOKEN               PaymentMethodTypeEnum = "SpreedlyToken"
)

// PurchaseMethodEnum is a string enum.
type PurchaseMethodEnum string

// MarshalJSON implements the json.Marshaler interface for PurchaseMethodEnum.
// It customizes the JSON marshaling process for PurchaseMethodEnum objects.
func (e PurchaseMethodEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for PurchaseMethodEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for PurchaseMethodEnum.
// It customizes the JSON unmarshaling process for PurchaseMethodEnum objects.
func (e *PurchaseMethodEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = PurchaseMethodEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to PurchaseMethodEnum")
    }
    return nil
}

// Checks whether the value is actually a member of PurchaseMethodEnum.
func (e PurchaseMethodEnum) isValid() bool {
    switch e {
    case PurchaseMethodEnum_INSTORE,
        PurchaseMethodEnum_PHONEORDER,
        PurchaseMethodEnum_ECOMMERCE:
        return true
    }
    return false
}

const (
    PurchaseMethodEnum_INSTORE    PurchaseMethodEnum = "InStore"
    PurchaseMethodEnum_PHONEORDER PurchaseMethodEnum = "PhoneOrder"
    PurchaseMethodEnum_ECOMMERCE  PurchaseMethodEnum = "ECommerce"
)

// CardTypeEnum is a string enum.
type CardTypeEnum string

// MarshalJSON implements the json.Marshaler interface for CardTypeEnum.
// It customizes the JSON marshaling process for CardTypeEnum objects.
func (e CardTypeEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for CardTypeEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for CardTypeEnum.
// It customizes the JSON unmarshaling process for CardTypeEnum objects.
func (e *CardTypeEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = CardTypeEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to CardTypeEnum")
    }
    return nil
}

// Checks whether the value is actually a member of CardTypeEnum.
func (e CardTypeEnum) isValid() bool {
    switch e {
    case CardTypeEnum_CREDIT,
        CardTypeEnum_DEBIT,
        CardTypeEnum_CHARGE,
        CardTypeEnum_OTHER,
        CardTypeEnum_PREPAID,
        CardTypeEnum_VISADEFERREDDEBIT,
        CardTypeEnum_NETWORKONLY:
        return true
    }
    return false
}

const (
    CardTypeEnum_CREDIT            CardTypeEnum = "Credit"
    CardTypeEnum_DEBIT             CardTypeEnum = "Debit"
    CardTypeEnum_CHARGE            CardTypeEnum = "Charge"
    CardTypeEnum_OTHER             CardTypeEnum = "Other"
    CardTypeEnum_PREPAID           CardTypeEnum = "Prepaid"
    CardTypeEnum_VISADEFERREDDEBIT CardTypeEnum = "VisaDeferredDebit"
    CardTypeEnum_NETWORKONLY       CardTypeEnum = "NetworkOnly"
)

// InstallmentStatusEnum is a string enum.
type InstallmentStatusEnum string

// MarshalJSON implements the json.Marshaler interface for InstallmentStatusEnum.
// It customizes the JSON marshaling process for InstallmentStatusEnum objects.
func (e InstallmentStatusEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for InstallmentStatusEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentStatusEnum.
// It customizes the JSON unmarshaling process for InstallmentStatusEnum objects.
func (e *InstallmentStatusEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = InstallmentStatusEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to InstallmentStatusEnum")
    }
    return nil
}

// Checks whether the value is actually a member of InstallmentStatusEnum.
func (e InstallmentStatusEnum) isValid() bool {
    switch e {
    case InstallmentStatusEnum_PENDING,
        InstallmentStatusEnum_PROCESSED,
        InstallmentStatusEnum_CANCELED:
        return true
    }
    return false
}

const (
    InstallmentStatusEnum_PENDING   InstallmentStatusEnum = "Pending"
    InstallmentStatusEnum_PROCESSED InstallmentStatusEnum = "Processed"
    InstallmentStatusEnum_CANCELED  InstallmentStatusEnum = "Canceled"
)

// RefundStrategyEnum is a string enum.
type RefundStrategyEnum string

// MarshalJSON implements the json.Marshaler interface for RefundStrategyEnum.
// It customizes the JSON marshaling process for RefundStrategyEnum objects.
func (e RefundStrategyEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for RefundStrategyEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for RefundStrategyEnum.
// It customizes the JSON unmarshaling process for RefundStrategyEnum objects.
func (e *RefundStrategyEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = RefundStrategyEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to RefundStrategyEnum")
    }
    return nil
}

// Checks whether the value is actually a member of RefundStrategyEnum.
func (e RefundStrategyEnum) isValid() bool {
    switch e {
    case RefundStrategyEnum_FUTUREINSTALLMENTSFIRST,
        RefundStrategyEnum_FUTUREINSTALLMENTSLAST,
        RefundStrategyEnum_FUTUREINSTALLMENTSNOTALLOWED,
        RefundStrategyEnum_REDUCEFROMLASTINSTALLMENT:
        return true
    }
    return false
}

const (
    RefundStrategyEnum_FUTUREINSTALLMENTSFIRST      RefundStrategyEnum = "FutureInstallmentsFirst"
    RefundStrategyEnum_FUTUREINSTALLMENTSLAST       RefundStrategyEnum = "FutureInstallmentsLast"
    RefundStrategyEnum_FUTUREINSTALLMENTSNOTALLOWED RefundStrategyEnum = "FutureInstallmentsNotAllowed"
    RefundStrategyEnum_REDUCEFROMLASTINSTALLMENT    RefundStrategyEnum = "ReduceFromLastInstallment"
)

// OAuthProviderErrorEnum is a string enum.
// OAuth 2 Authorization error codes
type OAuthProviderErrorEnum string

// MarshalJSON implements the json.Marshaler interface for OAuthProviderErrorEnum.
// It customizes the JSON marshaling process for OAuthProviderErrorEnum objects.
func (e OAuthProviderErrorEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for OAuthProviderErrorEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for OAuthProviderErrorEnum.
// It customizes the JSON unmarshaling process for OAuthProviderErrorEnum objects.
func (e *OAuthProviderErrorEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = OAuthProviderErrorEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to OAuthProviderErrorEnum")
    }
    return nil
}

// Checks whether the value is actually a member of OAuthProviderErrorEnum.
func (e OAuthProviderErrorEnum) isValid() bool {
    switch e {
    case OAuthProviderErrorEnum_INVALIDREQUEST,
        OAuthProviderErrorEnum_INVALIDCLIENT,
        OAuthProviderErrorEnum_INVALIDGRANT,
        OAuthProviderErrorEnum_UNAUTHORIZEDCLIENT,
        OAuthProviderErrorEnum_UNSUPPORTEDGRANTTYPE,
        OAuthProviderErrorEnum_INVALIDSCOPE:
        return true
    }
    return false
}

const (
    OAuthProviderErrorEnum_INVALIDREQUEST       OAuthProviderErrorEnum = "invalid_request"
    OAuthProviderErrorEnum_INVALIDCLIENT        OAuthProviderErrorEnum = "invalid_client"
    OAuthProviderErrorEnum_INVALIDGRANT         OAuthProviderErrorEnum = "invalid_grant"
    OAuthProviderErrorEnum_UNAUTHORIZEDCLIENT   OAuthProviderErrorEnum = "unauthorized_client"
    OAuthProviderErrorEnum_UNSUPPORTEDGRANTTYPE OAuthProviderErrorEnum = "unsupported_grant_type"
    OAuthProviderErrorEnum_INVALIDSCOPE         OAuthProviderErrorEnum = "invalid_scope"
)

// OAuthScopeOAuth2SandboxEnum is a string enum.
// OAuth 2 scopes supported by the API
type OAuthScopeOAuth2SandboxEnum string

// MarshalJSON implements the json.Marshaler interface for OAuthScopeOAuth2SandboxEnum.
// It customizes the JSON marshaling process for OAuthScopeOAuth2SandboxEnum objects.
func (e OAuthScopeOAuth2SandboxEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for OAuthScopeOAuth2SandboxEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for OAuthScopeOAuth2SandboxEnum.
// It customizes the JSON unmarshaling process for OAuthScopeOAuth2SandboxEnum objects.
func (e *OAuthScopeOAuth2SandboxEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = OAuthScopeOAuth2SandboxEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to OAuthScopeOAuth2SandboxEnum")
    }
    return nil
}

// Checks whether the value is actually a member of OAuthScopeOAuth2SandboxEnum.
func (e OAuthScopeOAuth2SandboxEnum) isValid() bool {
    switch e {
    case OAuthScopeOAuth2SandboxEnum_APIV3:
        return true
    }
    return false
}

const (
    OAuthScopeOAuth2SandboxEnum_APIV3 OAuthScopeOAuth2SandboxEnum = "api.v3"
)

// OAuthScopeOAuth2ProductionEnum is a string enum.
// OAuth 2 scopes supported by the API
type OAuthScopeOAuth2ProductionEnum string

// MarshalJSON implements the json.Marshaler interface for OAuthScopeOAuth2ProductionEnum.
// It customizes the JSON marshaling process for OAuthScopeOAuth2ProductionEnum objects.
func (e OAuthScopeOAuth2ProductionEnum) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for OAuthScopeOAuth2ProductionEnum")
}

// UnmarshalJSON implements the json.Unmarshaler interface for OAuthScopeOAuth2ProductionEnum.
// It customizes the JSON unmarshaling process for OAuthScopeOAuth2ProductionEnum objects.
func (e *OAuthScopeOAuth2ProductionEnum) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = OAuthScopeOAuth2ProductionEnum(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to OAuthScopeOAuth2ProductionEnum")
    }
    return nil
}

// Checks whether the value is actually a member of OAuthScopeOAuth2ProductionEnum.
func (e OAuthScopeOAuth2ProductionEnum) isValid() bool {
    switch e {
    case OAuthScopeOAuth2ProductionEnum_APIV3:
        return true
    }
    return false
}

const (
    OAuthScopeOAuth2ProductionEnum_APIV3 OAuthScopeOAuth2ProductionEnum = "api.v3"
)
