// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ErrorExtended represents a ErrorExtended struct.
type ErrorExtended struct {
    Code                 *string                `json:"Code,omitempty"`
    Message              *string                `json:"Message,omitempty"`
    AdditionalInfo       *string                `json:"AdditionalInfo,omitempty"`
    ExtraData            map[string]string      `json:"ExtraData,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ErrorExtended,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e ErrorExtended) String() string {
    return fmt.Sprintf(
    	"ErrorExtended[Code=%v, Message=%v, AdditionalInfo=%v, ExtraData=%v, AdditionalProperties=%v]",
    	e.Code, e.Message, e.AdditionalInfo, e.ExtraData, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ErrorExtended.
// It customizes the JSON marshaling process for ErrorExtended objects.
func (e ErrorExtended) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "Code", "Message", "AdditionalInfo", "ExtraData"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the ErrorExtended object to a map representation for JSON marshaling.
func (e ErrorExtended) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.Code != nil {
        structMap["Code"] = e.Code
    }
    if e.Message != nil {
        structMap["Message"] = e.Message
    }
    if e.AdditionalInfo != nil {
        structMap["AdditionalInfo"] = e.AdditionalInfo
    }
    if e.ExtraData != nil {
        structMap["ExtraData"] = e.ExtraData
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ErrorExtended.
// It customizes the JSON unmarshaling process for ErrorExtended objects.
func (e *ErrorExtended) UnmarshalJSON(input []byte) error {
    var temp tempErrorExtended
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Code", "Message", "AdditionalInfo", "ExtraData")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.Code = temp.Code
    e.Message = temp.Message
    e.AdditionalInfo = temp.AdditionalInfo
    e.ExtraData = temp.ExtraData
    return nil
}

// tempErrorExtended is a temporary struct used for validating the fields of ErrorExtended.
type tempErrorExtended  struct {
    Code           *string           `json:"Code,omitempty"`
    Message        *string           `json:"Message,omitempty"`
    AdditionalInfo *string           `json:"AdditionalInfo,omitempty"`
    ExtraData      map[string]string `json:"ExtraData,omitempty"`
}
