// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// EventsEndpointsModel represents a EventsEndpointsModel struct.
type EventsEndpointsModel struct {
    CreateSucceeded      *string                `json:"CreateSucceeded,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EventsEndpointsModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EventsEndpointsModel) String() string {
    return fmt.Sprintf(
    	"EventsEndpointsModel[CreateSucceeded=%v, AdditionalProperties=%v]",
    	e.CreateSucceeded, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EventsEndpointsModel.
// It customizes the JSON marshaling process for EventsEndpointsModel objects.
func (e EventsEndpointsModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "CreateSucceeded"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EventsEndpointsModel object to a map representation for JSON marshaling.
func (e EventsEndpointsModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.CreateSucceeded != nil {
        structMap["CreateSucceeded"] = e.CreateSucceeded
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventsEndpointsModel.
// It customizes the JSON unmarshaling process for EventsEndpointsModel objects.
func (e *EventsEndpointsModel) UnmarshalJSON(input []byte) error {
    var temp tempEventsEndpointsModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "CreateSucceeded")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.CreateSucceeded = temp.CreateSucceeded
    return nil
}

// tempEventsEndpointsModel is a temporary struct used for validating the fields of EventsEndpointsModel.
type tempEventsEndpointsModel  struct {
    CreateSucceeded *string `json:"CreateSucceeded,omitempty"`
}
