// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// GatewayTokenData represents a GatewayTokenData struct.
type GatewayTokenData struct {
    Token                *string                `json:"Token,omitempty"`
    Last4Digit           *string                `json:"Last4Digit,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for GatewayTokenData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (g GatewayTokenData) String() string {
    return fmt.Sprintf(
    	"GatewayTokenData[Token=%v, Last4Digit=%v, AdditionalProperties=%v]",
    	g.Token, g.Last4Digit, g.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for GatewayTokenData.
// It customizes the JSON marshaling process for GatewayTokenData objects.
func (g GatewayTokenData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(g.AdditionalProperties,
        "Token", "Last4Digit"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(g.toMap())
}

// toMap converts the GatewayTokenData object to a map representation for JSON marshaling.
func (g GatewayTokenData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, g.AdditionalProperties)
    if g.Token != nil {
        structMap["Token"] = g.Token
    }
    if g.Last4Digit != nil {
        structMap["Last4Digit"] = g.Last4Digit
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for GatewayTokenData.
// It customizes the JSON unmarshaling process for GatewayTokenData objects.
func (g *GatewayTokenData) UnmarshalJSON(input []byte) error {
    var temp tempGatewayTokenData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Token", "Last4Digit")
    if err != nil {
    	return err
    }
    g.AdditionalProperties = additionalProperties
    
    g.Token = temp.Token
    g.Last4Digit = temp.Last4Digit
    return nil
}

// tempGatewayTokenData is a temporary struct used for validating the fields of GatewayTokenData.
type tempGatewayTokenData  struct {
    Token      *string `json:"Token,omitempty"`
    Last4Digit *string `json:"Last4Digit,omitempty"`
}
