// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// IdentifierContract represents a IdentifierContract struct.
type IdentifierContract struct {
    RefOrderNumber        *string                `json:"RefOrderNumber,omitempty"`
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    ExtendedParams        map[string]string      `json:"ExtendedParams,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for IdentifierContract,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i IdentifierContract) String() string {
    return fmt.Sprintf(
    	"IdentifierContract[RefOrderNumber=%v, InstallmentPlanNumber=%v, ExtendedParams=%v, AdditionalProperties=%v]",
    	i.RefOrderNumber, i.InstallmentPlanNumber, i.ExtendedParams, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for IdentifierContract.
// It customizes the JSON marshaling process for IdentifierContract objects.
func (i IdentifierContract) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "RefOrderNumber", "InstallmentPlanNumber", "ExtendedParams"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the IdentifierContract object to a map representation for JSON marshaling.
func (i IdentifierContract) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = i.InstallmentPlanNumber
    }
    if i.ExtendedParams != nil {
        structMap["ExtendedParams"] = i.ExtendedParams
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for IdentifierContract.
// It customizes the JSON unmarshaling process for IdentifierContract objects.
func (i *IdentifierContract) UnmarshalJSON(input []byte) error {
    var temp tempIdentifierContract
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefOrderNumber", "InstallmentPlanNumber", "ExtendedParams")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.RefOrderNumber = temp.RefOrderNumber
    i.InstallmentPlanNumber = temp.InstallmentPlanNumber
    i.ExtendedParams = temp.ExtendedParams
    return nil
}

// tempIdentifierContract is a temporary struct used for validating the fields of IdentifierContract.
type tempIdentifierContract  struct {
    RefOrderNumber        *string           `json:"RefOrderNumber,omitempty"`
    InstallmentPlanNumber *string           `json:"InstallmentPlanNumber,omitempty"`
    ExtendedParams        map[string]string `json:"ExtendedParams,omitempty"`
}
