// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InitiateRedirectionEndpointsModel represents a InitiateRedirectionEndpointsModel struct.
type InitiateRedirectionEndpointsModel struct {
    Succeeded            *string                `json:"Succeeded,omitempty"`
    Failed               *string                `json:"Failed,omitempty"`
    Cancel               *string                `json:"Cancel,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InitiateRedirectionEndpointsModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InitiateRedirectionEndpointsModel) String() string {
    return fmt.Sprintf(
    	"InitiateRedirectionEndpointsModel[Succeeded=%v, Failed=%v, Cancel=%v, AdditionalProperties=%v]",
    	i.Succeeded, i.Failed, i.Cancel, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InitiateRedirectionEndpointsModel.
// It customizes the JSON marshaling process for InitiateRedirectionEndpointsModel objects.
func (i InitiateRedirectionEndpointsModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "Succeeded", "Failed", "Cancel"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InitiateRedirectionEndpointsModel object to a map representation for JSON marshaling.
func (i InitiateRedirectionEndpointsModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.Succeeded != nil {
        structMap["Succeeded"] = i.Succeeded
    }
    if i.Failed != nil {
        structMap["Failed"] = i.Failed
    }
    if i.Cancel != nil {
        structMap["Cancel"] = i.Cancel
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InitiateRedirectionEndpointsModel.
// It customizes the JSON unmarshaling process for InitiateRedirectionEndpointsModel objects.
func (i *InitiateRedirectionEndpointsModel) UnmarshalJSON(input []byte) error {
    var temp tempInitiateRedirectionEndpointsModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Succeeded", "Failed", "Cancel")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Succeeded = temp.Succeeded
    i.Failed = temp.Failed
    i.Cancel = temp.Cancel
    return nil
}

// tempInitiateRedirectionEndpointsModel is a temporary struct used for validating the fields of InitiateRedirectionEndpointsModel.
type tempInitiateRedirectionEndpointsModel  struct {
    Succeeded *string `json:"Succeeded,omitempty"`
    Failed    *string `json:"Failed,omitempty"`
    Cancel    *string `json:"Cancel,omitempty"`
}
