// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// InitiatePlanResponse represents a InitiatePlanResponse struct.
type InitiatePlanResponse struct {
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    RefOrderNumber        *string                `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum    `json:"PurchaseMethod,omitempty"`
    Status                PlanStatusEnum         `json:"Status"`
    Currency              *string                `json:"Currency,omitempty"`
    Amount                *float64               `json:"Amount,omitempty"`
    ExtendedParams        map[string]string      `json:"ExtendedParams,omitempty"`
    Shopper               *ShopperData           `json:"Shopper,omitempty"`
    BillingAddress        *AddressData           `json:"BillingAddress,omitempty"`
    CheckoutUrl           *string                `json:"CheckoutUrl,omitempty"`
    PrincipalAmount       *float64               `json:"PrincipalAmount,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InitiatePlanResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InitiatePlanResponse) String() string {
    return fmt.Sprintf(
    	"InitiatePlanResponse[InstallmentPlanNumber=%v, RefOrderNumber=%v, PurchaseMethod=%v, Status=%v, Currency=%v, Amount=%v, ExtendedParams=%v, Shopper=%v, BillingAddress=%v, CheckoutUrl=%v, PrincipalAmount=%v, AdditionalProperties=%v]",
    	i.InstallmentPlanNumber, i.RefOrderNumber, i.PurchaseMethod, i.Status, i.Currency, i.Amount, i.ExtendedParams, i.Shopper, i.BillingAddress, i.CheckoutUrl, i.PrincipalAmount, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InitiatePlanResponse.
// It customizes the JSON marshaling process for InitiatePlanResponse objects.
func (i InitiatePlanResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "InstallmentPlanNumber", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "Amount", "ExtendedParams", "Shopper", "BillingAddress", "CheckoutUrl", "PrincipalAmount"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InitiatePlanResponse object to a map representation for JSON marshaling.
func (i InitiatePlanResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = i.InstallmentPlanNumber
    }
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.PurchaseMethod != nil {
        structMap["PurchaseMethod"] = i.PurchaseMethod
    }
    structMap["Status"] = i.Status
    if i.Currency != nil {
        structMap["Currency"] = i.Currency
    }
    if i.Amount != nil {
        structMap["Amount"] = i.Amount
    }
    if i.ExtendedParams != nil {
        structMap["ExtendedParams"] = i.ExtendedParams
    }
    if i.Shopper != nil {
        structMap["Shopper"] = i.Shopper.toMap()
    }
    if i.BillingAddress != nil {
        structMap["BillingAddress"] = i.BillingAddress.toMap()
    }
    if i.CheckoutUrl != nil {
        structMap["CheckoutUrl"] = i.CheckoutUrl
    }
    if i.PrincipalAmount != nil {
        structMap["PrincipalAmount"] = i.PrincipalAmount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InitiatePlanResponse.
// It customizes the JSON unmarshaling process for InitiatePlanResponse objects.
func (i *InitiatePlanResponse) UnmarshalJSON(input []byte) error {
    var temp tempInitiatePlanResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "InstallmentPlanNumber", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "Amount", "ExtendedParams", "Shopper", "BillingAddress", "CheckoutUrl", "PrincipalAmount")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.InstallmentPlanNumber = temp.InstallmentPlanNumber
    i.RefOrderNumber = temp.RefOrderNumber
    i.PurchaseMethod = temp.PurchaseMethod
    i.Status = *temp.Status
    i.Currency = temp.Currency
    i.Amount = temp.Amount
    i.ExtendedParams = temp.ExtendedParams
    i.Shopper = temp.Shopper
    i.BillingAddress = temp.BillingAddress
    i.CheckoutUrl = temp.CheckoutUrl
    i.PrincipalAmount = temp.PrincipalAmount
    return nil
}

// tempInitiatePlanResponse is a temporary struct used for validating the fields of InitiatePlanResponse.
type tempInitiatePlanResponse  struct {
    InstallmentPlanNumber *string             `json:"InstallmentPlanNumber,omitempty"`
    RefOrderNumber        *string             `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum `json:"PurchaseMethod,omitempty"`
    Status                *PlanStatusEnum     `json:"Status"`
    Currency              *string             `json:"Currency,omitempty"`
    Amount                *float64            `json:"Amount,omitempty"`
    ExtendedParams        map[string]string   `json:"ExtendedParams,omitempty"`
    Shopper               *ShopperData        `json:"Shopper,omitempty"`
    BillingAddress        *AddressData        `json:"BillingAddress,omitempty"`
    CheckoutUrl           *string             `json:"CheckoutUrl,omitempty"`
    PrincipalAmount       *float64            `json:"PrincipalAmount,omitempty"`
}

func (i *tempInitiatePlanResponse) validate() error {
    var errs []string
    if i.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `InitiatePlanResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
