// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentPlanRefundResponse represents a InstallmentPlanRefundResponse struct.
type InstallmentPlanRefundResponse struct {
    RefundId              *string                `json:"RefundId,omitempty"`
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    Currency              *string                `json:"Currency,omitempty"`
    NonCreditRefundAmount *float64               `json:"NonCreditRefundAmount,omitempty"`
    CreditRefundAmount    *float64               `json:"CreditRefundAmount,omitempty"`
    Summary               *RefundSummary         `json:"Summary,omitempty"`
    ReferenceId           *string                `json:"ReferenceId,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanRefundResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanRefundResponse) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanRefundResponse[RefundId=%v, InstallmentPlanNumber=%v, Currency=%v, NonCreditRefundAmount=%v, CreditRefundAmount=%v, Summary=%v, ReferenceId=%v, AdditionalProperties=%v]",
    	i.RefundId, i.InstallmentPlanNumber, i.Currency, i.NonCreditRefundAmount, i.CreditRefundAmount, i.Summary, i.ReferenceId, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanRefundResponse.
// It customizes the JSON marshaling process for InstallmentPlanRefundResponse objects.
func (i InstallmentPlanRefundResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "RefundId", "InstallmentPlanNumber", "Currency", "NonCreditRefundAmount", "CreditRefundAmount", "Summary", "ReferenceId"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanRefundResponse object to a map representation for JSON marshaling.
func (i InstallmentPlanRefundResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.RefundId != nil {
        structMap["RefundId"] = i.RefundId
    }
    if i.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = i.InstallmentPlanNumber
    }
    if i.Currency != nil {
        structMap["Currency"] = i.Currency
    }
    if i.NonCreditRefundAmount != nil {
        structMap["NonCreditRefundAmount"] = i.NonCreditRefundAmount
    }
    if i.CreditRefundAmount != nil {
        structMap["CreditRefundAmount"] = i.CreditRefundAmount
    }
    if i.Summary != nil {
        structMap["Summary"] = i.Summary.toMap()
    }
    if i.ReferenceId != nil {
        structMap["ReferenceId"] = i.ReferenceId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanRefundResponse.
// It customizes the JSON unmarshaling process for InstallmentPlanRefundResponse objects.
func (i *InstallmentPlanRefundResponse) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanRefundResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefundId", "InstallmentPlanNumber", "Currency", "NonCreditRefundAmount", "CreditRefundAmount", "Summary", "ReferenceId")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.RefundId = temp.RefundId
    i.InstallmentPlanNumber = temp.InstallmentPlanNumber
    i.Currency = temp.Currency
    i.NonCreditRefundAmount = temp.NonCreditRefundAmount
    i.CreditRefundAmount = temp.CreditRefundAmount
    i.Summary = temp.Summary
    i.ReferenceId = temp.ReferenceId
    return nil
}

// tempInstallmentPlanRefundResponse is a temporary struct used for validating the fields of InstallmentPlanRefundResponse.
type tempInstallmentPlanRefundResponse  struct {
    RefundId              *string        `json:"RefundId,omitempty"`
    InstallmentPlanNumber *string        `json:"InstallmentPlanNumber,omitempty"`
    Currency              *string        `json:"Currency,omitempty"`
    NonCreditRefundAmount *float64       `json:"NonCreditRefundAmount,omitempty"`
    CreditRefundAmount    *float64       `json:"CreditRefundAmount,omitempty"`
    Summary               *RefundSummary `json:"Summary,omitempty"`
    ReferenceId           *string        `json:"ReferenceId,omitempty"`
}
