// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// Installment represents a Installment struct.
type Installment struct {
    InstallmentNumber    int                    `json:"InstallmentNumber"`
    Amount               float64                `json:"Amount"`
    ProcessDateTime      *time.Time             `json:"ProcessDateTime,omitempty"`
    Status               InstallmentStatusEnum  `json:"Status"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Installment,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i Installment) String() string {
    return fmt.Sprintf(
    	"Installment[InstallmentNumber=%v, Amount=%v, ProcessDateTime=%v, Status=%v, AdditionalProperties=%v]",
    	i.InstallmentNumber, i.Amount, i.ProcessDateTime, i.Status, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Installment.
// It customizes the JSON marshaling process for Installment objects.
func (i Installment) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "InstallmentNumber", "Amount", "ProcessDateTime", "Status"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the Installment object to a map representation for JSON marshaling.
func (i Installment) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    structMap["InstallmentNumber"] = i.InstallmentNumber
    structMap["Amount"] = i.Amount
    if i.ProcessDateTime != nil {
        structMap["ProcessDateTime"] = i.ProcessDateTime.Format(time.RFC3339)
    }
    structMap["Status"] = i.Status
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Installment.
// It customizes the JSON unmarshaling process for Installment objects.
func (i *Installment) UnmarshalJSON(input []byte) error {
    var temp tempInstallment
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "InstallmentNumber", "Amount", "ProcessDateTime", "Status")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.InstallmentNumber = *temp.InstallmentNumber
    i.Amount = *temp.Amount
    if temp.ProcessDateTime != nil {
        ProcessDateTimeVal, err := time.Parse(time.RFC3339, *temp.ProcessDateTime)
        if err != nil {
            log.Fatalf("Cannot Parse ProcessDateTime as % s format.", time.RFC3339)
        }
        i.ProcessDateTime = &ProcessDateTimeVal
    }
    i.Status = *temp.Status
    return nil
}

// tempInstallment is a temporary struct used for validating the fields of Installment.
type tempInstallment  struct {
    InstallmentNumber *int                   `json:"InstallmentNumber"`
    Amount            *float64               `json:"Amount"`
    ProcessDateTime   *string                `json:"ProcessDateTime,omitempty"`
    Status            *InstallmentStatusEnum `json:"Status"`
}

func (i *tempInstallment) validate() error {
    var errs []string
    if i.InstallmentNumber == nil {
        errs = append(errs, "required field `InstallmentNumber` is missing for type `Installment`")
    }
    if i.Amount == nil {
        errs = append(errs, "required field `Amount` is missing for type `Installment`")
    }
    if i.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `Installment`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
