// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// InstallmentPlanRefundRequest represents a InstallmentPlanRefundRequest struct.
type InstallmentPlanRefundRequest struct {
    Amount               string                 `json:"Amount"`
    RefundStrategy       *RefundStrategyEnum    `json:"RefundStrategy,omitempty"`
    ReferenceId          *string                `json:"ReferenceId,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanRefundRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanRefundRequest) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanRefundRequest[Amount=%v, RefundStrategy=%v, ReferenceId=%v, AdditionalProperties=%v]",
    	i.Amount, i.RefundStrategy, i.ReferenceId, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanRefundRequest.
// It customizes the JSON marshaling process for InstallmentPlanRefundRequest objects.
func (i InstallmentPlanRefundRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "Amount", "RefundStrategy", "ReferenceId"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanRefundRequest object to a map representation for JSON marshaling.
func (i InstallmentPlanRefundRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    structMap["Amount"] = i.Amount
    if i.RefundStrategy != nil {
        structMap["RefundStrategy"] = i.RefundStrategy
    }
    if i.ReferenceId != nil {
        structMap["ReferenceId"] = i.ReferenceId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanRefundRequest.
// It customizes the JSON unmarshaling process for InstallmentPlanRefundRequest objects.
func (i *InstallmentPlanRefundRequest) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanRefundRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Amount", "RefundStrategy", "ReferenceId")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Amount = *temp.Amount
    i.RefundStrategy = temp.RefundStrategy
    i.ReferenceId = temp.ReferenceId
    return nil
}

// tempInstallmentPlanRefundRequest is a temporary struct used for validating the fields of InstallmentPlanRefundRequest.
type tempInstallmentPlanRefundRequest  struct {
    Amount         *string             `json:"Amount"`
    RefundStrategy *RefundStrategyEnum `json:"RefundStrategy,omitempty"`
    ReferenceId    *string             `json:"ReferenceId,omitempty"`
}

func (i *tempInstallmentPlanRefundRequest) validate() error {
    var errs []string
    if i.Amount == nil {
        errs = append(errs, "required field `Amount` is missing for type `InstallmentPlanRefundRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
