// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentsEligibilityResponse represents a InstallmentsEligibilityResponse struct.
type InstallmentsEligibilityResponse struct {
    InstallmentProvider  *string                  `json:"InstallmentProvider,omitempty"`
    PaymentPlanOptions   []PaymentPlanOptionModel `json:"PaymentPlanOptions,omitempty"`
    AdditionalProperties map[string]interface{}   `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentsEligibilityResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentsEligibilityResponse) String() string {
    return fmt.Sprintf(
    	"InstallmentsEligibilityResponse[InstallmentProvider=%v, PaymentPlanOptions=%v, AdditionalProperties=%v]",
    	i.InstallmentProvider, i.PaymentPlanOptions, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentsEligibilityResponse.
// It customizes the JSON marshaling process for InstallmentsEligibilityResponse objects.
func (i InstallmentsEligibilityResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "InstallmentProvider", "PaymentPlanOptions"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentsEligibilityResponse object to a map representation for JSON marshaling.
func (i InstallmentsEligibilityResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.InstallmentProvider != nil {
        structMap["InstallmentProvider"] = i.InstallmentProvider
    }
    if i.PaymentPlanOptions != nil {
        structMap["PaymentPlanOptions"] = i.PaymentPlanOptions
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentsEligibilityResponse.
// It customizes the JSON unmarshaling process for InstallmentsEligibilityResponse objects.
func (i *InstallmentsEligibilityResponse) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentsEligibilityResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "InstallmentProvider", "PaymentPlanOptions")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.InstallmentProvider = temp.InstallmentProvider
    i.PaymentPlanOptions = temp.PaymentPlanOptions
    return nil
}

// tempInstallmentsEligibilityResponse is a temporary struct used for validating the fields of InstallmentsEligibilityResponse.
type tempInstallmentsEligibilityResponse  struct {
    InstallmentProvider *string                  `json:"InstallmentProvider,omitempty"`
    PaymentPlanOptions  []PaymentPlanOptionModel `json:"PaymentPlanOptions,omitempty"`
}
