// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// InstallmentPlanCreateRequest represents a InstallmentPlanCreateRequest struct.
type InstallmentPlanCreateRequest struct {
    AutoCapture                bool                       `json:"AutoCapture"`
    Attempt3dSecure            *bool                      `json:"Attempt3dSecure,omitempty"`
    TermsAndConditionsAccepted bool                       `json:"TermsAndConditionsAccepted"`
    Shopper                    *ShopperData               `json:"Shopper,omitempty"`
    PlanData                   *PlanDataModel             `json:"PlanData,omitempty"`
    BillingAddress             *AddressDataModel          `json:"BillingAddress,omitempty"`
    PaymentMethod              *PaymentMethodModel        `json:"PaymentMethod,omitempty"`
    RedirectUrls               *RedirectionEndpointsModel `json:"RedirectUrls,omitempty"`
    ProcessingData             *ProcessingData            `json:"ProcessingData,omitempty"`
    EventsEndpoints            *EventsEndpointsModel      `json:"EventsEndpoints,omitempty"`
    AdditionalProperties       map[string]interface{}     `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanCreateRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanCreateRequest) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanCreateRequest[AutoCapture=%v, Attempt3dSecure=%v, TermsAndConditionsAccepted=%v, Shopper=%v, PlanData=%v, BillingAddress=%v, PaymentMethod=%v, RedirectUrls=%v, ProcessingData=%v, EventsEndpoints=%v, AdditionalProperties=%v]",
    	i.AutoCapture, i.Attempt3dSecure, i.TermsAndConditionsAccepted, i.Shopper, i.PlanData, i.BillingAddress, i.PaymentMethod, i.RedirectUrls, i.ProcessingData, i.EventsEndpoints, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanCreateRequest.
// It customizes the JSON marshaling process for InstallmentPlanCreateRequest objects.
func (i InstallmentPlanCreateRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "AutoCapture", "Attempt3dSecure", "TermsAndConditionsAccepted", "Shopper", "PlanData", "BillingAddress", "PaymentMethod", "RedirectUrls", "ProcessingData", "EventsEndpoints"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanCreateRequest object to a map representation for JSON marshaling.
func (i InstallmentPlanCreateRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    structMap["AutoCapture"] = i.AutoCapture
    if i.Attempt3dSecure != nil {
        structMap["Attempt3dSecure"] = i.Attempt3dSecure
    }
    structMap["TermsAndConditionsAccepted"] = i.TermsAndConditionsAccepted
    if i.Shopper != nil {
        structMap["Shopper"] = i.Shopper.toMap()
    }
    if i.PlanData != nil {
        structMap["PlanData"] = i.PlanData.toMap()
    }
    if i.BillingAddress != nil {
        structMap["BillingAddress"] = i.BillingAddress.toMap()
    }
    if i.PaymentMethod != nil {
        structMap["PaymentMethod"] = i.PaymentMethod.toMap()
    }
    if i.RedirectUrls != nil {
        structMap["RedirectUrls"] = i.RedirectUrls.toMap()
    }
    if i.ProcessingData != nil {
        structMap["ProcessingData"] = i.ProcessingData.toMap()
    }
    if i.EventsEndpoints != nil {
        structMap["EventsEndpoints"] = i.EventsEndpoints.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanCreateRequest.
// It customizes the JSON unmarshaling process for InstallmentPlanCreateRequest objects.
func (i *InstallmentPlanCreateRequest) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanCreateRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "AutoCapture", "Attempt3dSecure", "TermsAndConditionsAccepted", "Shopper", "PlanData", "BillingAddress", "PaymentMethod", "RedirectUrls", "ProcessingData", "EventsEndpoints")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.AutoCapture = *temp.AutoCapture
    i.Attempt3dSecure = temp.Attempt3dSecure
    i.TermsAndConditionsAccepted = *temp.TermsAndConditionsAccepted
    i.Shopper = temp.Shopper
    i.PlanData = temp.PlanData
    i.BillingAddress = temp.BillingAddress
    i.PaymentMethod = temp.PaymentMethod
    i.RedirectUrls = temp.RedirectUrls
    i.ProcessingData = temp.ProcessingData
    i.EventsEndpoints = temp.EventsEndpoints
    return nil
}

// tempInstallmentPlanCreateRequest is a temporary struct used for validating the fields of InstallmentPlanCreateRequest.
type tempInstallmentPlanCreateRequest  struct {
    AutoCapture                *bool                      `json:"AutoCapture"`
    Attempt3dSecure            *bool                      `json:"Attempt3dSecure,omitempty"`
    TermsAndConditionsAccepted *bool                      `json:"TermsAndConditionsAccepted"`
    Shopper                    *ShopperData               `json:"Shopper,omitempty"`
    PlanData                   *PlanDataModel             `json:"PlanData,omitempty"`
    BillingAddress             *AddressDataModel          `json:"BillingAddress,omitempty"`
    PaymentMethod              *PaymentMethodModel        `json:"PaymentMethod,omitempty"`
    RedirectUrls               *RedirectionEndpointsModel `json:"RedirectUrls,omitempty"`
    ProcessingData             *ProcessingData            `json:"ProcessingData,omitempty"`
    EventsEndpoints            *EventsEndpointsModel      `json:"EventsEndpoints,omitempty"`
}

func (i *tempInstallmentPlanCreateRequest) validate() error {
    var errs []string
    if i.AutoCapture == nil {
        errs = append(errs, "required field `AutoCapture` is missing for type `InstallmentPlanCreateRequest`")
    }
    if i.TermsAndConditionsAccepted == nil {
        errs = append(errs, "required field `TermsAndConditionsAccepted` is missing for type `InstallmentPlanCreateRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
