// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentPlanUpdateRequestByIdentifier represents a InstallmentPlanUpdateRequestByIdentifier struct.
type InstallmentPlanUpdateRequestByIdentifier struct {
    RefOrderNumber       *string                `json:"RefOrderNumber,omitempty"`
    TrackingNumber       *string                `json:"TrackingNumber,omitempty"`
    Capture              *bool                  `json:"Capture,omitempty"`
    ShippingStatus       *ShippingStatusEnum    `json:"ShippingStatus,omitempty"`
    NewAmount            *float64               `json:"NewAmount,omitempty"`
    Identifier           *IdentifierContract    `json:"Identifier,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanUpdateRequestByIdentifier,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanUpdateRequestByIdentifier) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanUpdateRequestByIdentifier[RefOrderNumber=%v, TrackingNumber=%v, Capture=%v, ShippingStatus=%v, NewAmount=%v, Identifier=%v, AdditionalProperties=%v]",
    	i.RefOrderNumber, i.TrackingNumber, i.Capture, i.ShippingStatus, i.NewAmount, i.Identifier, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanUpdateRequestByIdentifier.
// It customizes the JSON marshaling process for InstallmentPlanUpdateRequestByIdentifier objects.
func (i InstallmentPlanUpdateRequestByIdentifier) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "RefOrderNumber", "TrackingNumber", "Capture", "ShippingStatus", "NewAmount", "Identifier"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanUpdateRequestByIdentifier object to a map representation for JSON marshaling.
func (i InstallmentPlanUpdateRequestByIdentifier) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.TrackingNumber != nil {
        structMap["TrackingNumber"] = i.TrackingNumber
    }
    if i.Capture != nil {
        structMap["Capture"] = i.Capture
    }
    if i.ShippingStatus != nil {
        structMap["ShippingStatus"] = i.ShippingStatus
    }
    if i.NewAmount != nil {
        structMap["NewAmount"] = i.NewAmount
    }
    if i.Identifier != nil {
        structMap["Identifier"] = i.Identifier.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanUpdateRequestByIdentifier.
// It customizes the JSON unmarshaling process for InstallmentPlanUpdateRequestByIdentifier objects.
func (i *InstallmentPlanUpdateRequestByIdentifier) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanUpdateRequestByIdentifier
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefOrderNumber", "TrackingNumber", "Capture", "ShippingStatus", "NewAmount", "Identifier")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.RefOrderNumber = temp.RefOrderNumber
    i.TrackingNumber = temp.TrackingNumber
    i.Capture = temp.Capture
    i.ShippingStatus = temp.ShippingStatus
    i.NewAmount = temp.NewAmount
    i.Identifier = temp.Identifier
    return nil
}

// tempInstallmentPlanUpdateRequestByIdentifier is a temporary struct used for validating the fields of InstallmentPlanUpdateRequestByIdentifier.
type tempInstallmentPlanUpdateRequestByIdentifier  struct {
    RefOrderNumber *string             `json:"RefOrderNumber,omitempty"`
    TrackingNumber *string             `json:"TrackingNumber,omitempty"`
    Capture        *bool               `json:"Capture,omitempty"`
    ShippingStatus *ShippingStatusEnum `json:"ShippingStatus,omitempty"`
    NewAmount      *float64            `json:"NewAmount,omitempty"`
    Identifier     *IdentifierContract `json:"Identifier,omitempty"`
}
