// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// InstallmentPlanCreateResponse represents a InstallmentPlanCreateResponse struct.
type InstallmentPlanCreateResponse struct {
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    DateCreated           time.Time              `json:"DateCreated"`
    RefOrderNumber        *string                `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum    `json:"PurchaseMethod,omitempty"`
    Status                PlanStatusEnum         `json:"Status"`
    Currency              *string                `json:"Currency,omitempty"`
    OriginalAmount        *float64               `json:"OriginalAmount,omitempty"`
    Amount                *float64               `json:"Amount,omitempty"`
    ExtendedParams        map[string]string      `json:"ExtendedParams,omitempty"`
    Authorization         *AuthorizationModel    `json:"Authorization,omitempty"`
    Shopper               *ShopperData           `json:"Shopper,omitempty"`
    BillingAddress        *AddressData           `json:"BillingAddress,omitempty"`
    PaymentMethod         *PaymentMethodModel    `json:"PaymentMethod,omitempty"`
    Installments          []Installment          `json:"Installments,omitempty"`
    Links                 *LinksData             `json:"Links,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanCreateResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanCreateResponse) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanCreateResponse[InstallmentPlanNumber=%v, DateCreated=%v, RefOrderNumber=%v, PurchaseMethod=%v, Status=%v, Currency=%v, OriginalAmount=%v, Amount=%v, ExtendedParams=%v, Authorization=%v, Shopper=%v, BillingAddress=%v, PaymentMethod=%v, Installments=%v, Links=%v, AdditionalProperties=%v]",
    	i.InstallmentPlanNumber, i.DateCreated, i.RefOrderNumber, i.PurchaseMethod, i.Status, i.Currency, i.OriginalAmount, i.Amount, i.ExtendedParams, i.Authorization, i.Shopper, i.BillingAddress, i.PaymentMethod, i.Installments, i.Links, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanCreateResponse.
// It customizes the JSON marshaling process for InstallmentPlanCreateResponse objects.
func (i InstallmentPlanCreateResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "InstallmentPlanNumber", "DateCreated", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "OriginalAmount", "Amount", "ExtendedParams", "Authorization", "Shopper", "BillingAddress", "PaymentMethod", "Installments", "Links"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanCreateResponse object to a map representation for JSON marshaling.
func (i InstallmentPlanCreateResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = i.InstallmentPlanNumber
    }
    structMap["DateCreated"] = i.DateCreated.Format(time.RFC3339)
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.PurchaseMethod != nil {
        structMap["PurchaseMethod"] = i.PurchaseMethod
    }
    structMap["Status"] = i.Status
    if i.Currency != nil {
        structMap["Currency"] = i.Currency
    }
    if i.OriginalAmount != nil {
        structMap["OriginalAmount"] = i.OriginalAmount
    }
    if i.Amount != nil {
        structMap["Amount"] = i.Amount
    }
    if i.ExtendedParams != nil {
        structMap["ExtendedParams"] = i.ExtendedParams
    }
    if i.Authorization != nil {
        structMap["Authorization"] = i.Authorization.toMap()
    }
    if i.Shopper != nil {
        structMap["Shopper"] = i.Shopper.toMap()
    }
    if i.BillingAddress != nil {
        structMap["BillingAddress"] = i.BillingAddress.toMap()
    }
    if i.PaymentMethod != nil {
        structMap["PaymentMethod"] = i.PaymentMethod.toMap()
    }
    if i.Installments != nil {
        structMap["Installments"] = i.Installments
    }
    if i.Links != nil {
        structMap["Links"] = i.Links.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanCreateResponse.
// It customizes the JSON unmarshaling process for InstallmentPlanCreateResponse objects.
func (i *InstallmentPlanCreateResponse) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanCreateResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "InstallmentPlanNumber", "DateCreated", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "OriginalAmount", "Amount", "ExtendedParams", "Authorization", "Shopper", "BillingAddress", "PaymentMethod", "Installments", "Links")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.InstallmentPlanNumber = temp.InstallmentPlanNumber
    DateCreatedVal, err := time.Parse(time.RFC3339, *temp.DateCreated)
    if err != nil {
        log.Fatalf("Cannot Parse DateCreated as % s format.", time.RFC3339)
    }
    i.DateCreated = DateCreatedVal
    i.RefOrderNumber = temp.RefOrderNumber
    i.PurchaseMethod = temp.PurchaseMethod
    i.Status = *temp.Status
    i.Currency = temp.Currency
    i.OriginalAmount = temp.OriginalAmount
    i.Amount = temp.Amount
    i.ExtendedParams = temp.ExtendedParams
    i.Authorization = temp.Authorization
    i.Shopper = temp.Shopper
    i.BillingAddress = temp.BillingAddress
    i.PaymentMethod = temp.PaymentMethod
    i.Installments = temp.Installments
    i.Links = temp.Links
    return nil
}

// tempInstallmentPlanCreateResponse is a temporary struct used for validating the fields of InstallmentPlanCreateResponse.
type tempInstallmentPlanCreateResponse  struct {
    InstallmentPlanNumber *string             `json:"InstallmentPlanNumber,omitempty"`
    DateCreated           *string             `json:"DateCreated"`
    RefOrderNumber        *string             `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum `json:"PurchaseMethod,omitempty"`
    Status                *PlanStatusEnum     `json:"Status"`
    Currency              *string             `json:"Currency,omitempty"`
    OriginalAmount        *float64            `json:"OriginalAmount,omitempty"`
    Amount                *float64            `json:"Amount,omitempty"`
    ExtendedParams        map[string]string   `json:"ExtendedParams,omitempty"`
    Authorization         *AuthorizationModel `json:"Authorization,omitempty"`
    Shopper               *ShopperData        `json:"Shopper,omitempty"`
    BillingAddress        *AddressData        `json:"BillingAddress,omitempty"`
    PaymentMethod         *PaymentMethodModel `json:"PaymentMethod,omitempty"`
    Installments          []Installment       `json:"Installments,omitempty"`
    Links                 *LinksData          `json:"Links,omitempty"`
}

func (i *tempInstallmentPlanCreateResponse) validate() error {
    var errs []string
    if i.DateCreated == nil {
        errs = append(errs, "required field `DateCreated` is missing for type `InstallmentPlanCreateResponse`")
    }
    if i.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `InstallmentPlanCreateResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
