// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentPlanInitiateRequest represents a InstallmentPlanInitiateRequest struct.
type InstallmentPlanInitiateRequest struct {
    AutoCapture          *bool                              `json:"AutoCapture,omitempty"`
    Attempt3dSecure      *bool                              `json:"Attempt3dSecure,omitempty"`
    Shopper              *ShopperData                       `json:"Shopper,omitempty"`
    PlanData             *PlanDataModel                     `json:"PlanData,omitempty"`
    BillingAddress       *AddressDataModel                  `json:"BillingAddress,omitempty"`
    RedirectUrls         *InitiateRedirectionEndpointsModel `json:"RedirectUrls,omitempty"`
    UxSettings           *UxSettingsModel                   `json:"UxSettings,omitempty"`
    EventsEndpoints      *EventsEndpointsModel              `json:"EventsEndpoints,omitempty"`
    ProcessingData       *ProcessingData                    `json:"ProcessingData,omitempty"`
    AdditionalProperties map[string]interface{}             `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanInitiateRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanInitiateRequest) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanInitiateRequest[AutoCapture=%v, Attempt3dSecure=%v, Shopper=%v, PlanData=%v, BillingAddress=%v, RedirectUrls=%v, UxSettings=%v, EventsEndpoints=%v, ProcessingData=%v, AdditionalProperties=%v]",
    	i.AutoCapture, i.Attempt3dSecure, i.Shopper, i.PlanData, i.BillingAddress, i.RedirectUrls, i.UxSettings, i.EventsEndpoints, i.ProcessingData, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanInitiateRequest.
// It customizes the JSON marshaling process for InstallmentPlanInitiateRequest objects.
func (i InstallmentPlanInitiateRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "AutoCapture", "Attempt3dSecure", "Shopper", "PlanData", "BillingAddress", "RedirectUrls", "UxSettings", "EventsEndpoints", "ProcessingData"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanInitiateRequest object to a map representation for JSON marshaling.
func (i InstallmentPlanInitiateRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.AutoCapture != nil {
        structMap["AutoCapture"] = i.AutoCapture
    }
    if i.Attempt3dSecure != nil {
        structMap["Attempt3dSecure"] = i.Attempt3dSecure
    }
    if i.Shopper != nil {
        structMap["Shopper"] = i.Shopper.toMap()
    }
    if i.PlanData != nil {
        structMap["PlanData"] = i.PlanData.toMap()
    }
    if i.BillingAddress != nil {
        structMap["BillingAddress"] = i.BillingAddress.toMap()
    }
    if i.RedirectUrls != nil {
        structMap["RedirectUrls"] = i.RedirectUrls.toMap()
    }
    if i.UxSettings != nil {
        structMap["UxSettings"] = i.UxSettings.toMap()
    }
    if i.EventsEndpoints != nil {
        structMap["EventsEndpoints"] = i.EventsEndpoints.toMap()
    }
    if i.ProcessingData != nil {
        structMap["ProcessingData"] = i.ProcessingData.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanInitiateRequest.
// It customizes the JSON unmarshaling process for InstallmentPlanInitiateRequest objects.
func (i *InstallmentPlanInitiateRequest) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanInitiateRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "AutoCapture", "Attempt3dSecure", "Shopper", "PlanData", "BillingAddress", "RedirectUrls", "UxSettings", "EventsEndpoints", "ProcessingData")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.AutoCapture = temp.AutoCapture
    i.Attempt3dSecure = temp.Attempt3dSecure
    i.Shopper = temp.Shopper
    i.PlanData = temp.PlanData
    i.BillingAddress = temp.BillingAddress
    i.RedirectUrls = temp.RedirectUrls
    i.UxSettings = temp.UxSettings
    i.EventsEndpoints = temp.EventsEndpoints
    i.ProcessingData = temp.ProcessingData
    return nil
}

// tempInstallmentPlanInitiateRequest is a temporary struct used for validating the fields of InstallmentPlanInitiateRequest.
type tempInstallmentPlanInitiateRequest  struct {
    AutoCapture     *bool                              `json:"AutoCapture,omitempty"`
    Attempt3dSecure *bool                              `json:"Attempt3dSecure,omitempty"`
    Shopper         *ShopperData                       `json:"Shopper,omitempty"`
    PlanData        *PlanDataModel                     `json:"PlanData,omitempty"`
    BillingAddress  *AddressDataModel                  `json:"BillingAddress,omitempty"`
    RedirectUrls    *InitiateRedirectionEndpointsModel `json:"RedirectUrls,omitempty"`
    UxSettings      *UxSettingsModel                   `json:"UxSettings,omitempty"`
    EventsEndpoints *EventsEndpointsModel              `json:"EventsEndpoints,omitempty"`
    ProcessingData  *ProcessingData                    `json:"ProcessingData,omitempty"`
}
