// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// InstallmentPlanUpdateResponse represents a InstallmentPlanUpdateResponse struct.
type InstallmentPlanUpdateResponse struct {
    RefOrderNumber        *string                `json:"RefOrderNumber,omitempty"`
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    Status                PlanStatusEnum         `json:"Status"`
    ShippingStatus        ShippingStatusEnum     `json:"ShippingStatus"`
    NewAmount             *float64               `json:"NewAmount,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanUpdateResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanUpdateResponse) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanUpdateResponse[RefOrderNumber=%v, InstallmentPlanNumber=%v, Status=%v, ShippingStatus=%v, NewAmount=%v, AdditionalProperties=%v]",
    	i.RefOrderNumber, i.InstallmentPlanNumber, i.Status, i.ShippingStatus, i.NewAmount, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanUpdateResponse.
// It customizes the JSON marshaling process for InstallmentPlanUpdateResponse objects.
func (i InstallmentPlanUpdateResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "RefOrderNumber", "InstallmentPlanNumber", "Status", "ShippingStatus", "NewAmount"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanUpdateResponse object to a map representation for JSON marshaling.
func (i InstallmentPlanUpdateResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = i.InstallmentPlanNumber
    }
    structMap["Status"] = i.Status
    structMap["ShippingStatus"] = i.ShippingStatus
    if i.NewAmount != nil {
        structMap["NewAmount"] = i.NewAmount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanUpdateResponse.
// It customizes the JSON unmarshaling process for InstallmentPlanUpdateResponse objects.
func (i *InstallmentPlanUpdateResponse) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanUpdateResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefOrderNumber", "InstallmentPlanNumber", "Status", "ShippingStatus", "NewAmount")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.RefOrderNumber = temp.RefOrderNumber
    i.InstallmentPlanNumber = temp.InstallmentPlanNumber
    i.Status = *temp.Status
    i.ShippingStatus = *temp.ShippingStatus
    i.NewAmount = temp.NewAmount
    return nil
}

// tempInstallmentPlanUpdateResponse is a temporary struct used for validating the fields of InstallmentPlanUpdateResponse.
type tempInstallmentPlanUpdateResponse  struct {
    RefOrderNumber        *string             `json:"RefOrderNumber,omitempty"`
    InstallmentPlanNumber *string             `json:"InstallmentPlanNumber,omitempty"`
    Status                *PlanStatusEnum     `json:"Status"`
    ShippingStatus        *ShippingStatusEnum `json:"ShippingStatus"`
    NewAmount             *float64            `json:"NewAmount,omitempty"`
}

func (i *tempInstallmentPlanUpdateResponse) validate() error {
    var errs []string
    if i.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `InstallmentPlanUpdateResponse`")
    }
    if i.ShippingStatus == nil {
        errs = append(errs, "required field `ShippingStatus` is missing for type `InstallmentPlanUpdateResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
