// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentPlanSearchResponse represents a InstallmentPlanSearchResponse struct.
type InstallmentPlanSearchResponse struct {
    PlanList             []SearchInstallmentPlanResponseItem `json:"PlanList,omitempty"`
    AdditionalProperties map[string]interface{}              `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanSearchResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanSearchResponse) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanSearchResponse[PlanList=%v, AdditionalProperties=%v]",
    	i.PlanList, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanSearchResponse.
// It customizes the JSON marshaling process for InstallmentPlanSearchResponse objects.
func (i InstallmentPlanSearchResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "PlanList"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanSearchResponse object to a map representation for JSON marshaling.
func (i InstallmentPlanSearchResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.PlanList != nil {
        structMap["PlanList"] = i.PlanList
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanSearchResponse.
// It customizes the JSON unmarshaling process for InstallmentPlanSearchResponse objects.
func (i *InstallmentPlanSearchResponse) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanSearchResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "PlanList")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.PlanList = temp.PlanList
    return nil
}

// tempInstallmentPlanSearchResponse is a temporary struct used for validating the fields of InstallmentPlanSearchResponse.
type tempInstallmentPlanSearchResponse  struct {
    PlanList []SearchInstallmentPlanResponseItem `json:"PlanList,omitempty"`
}
