// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// InstallmentPlanUpdateRequest represents a InstallmentPlanUpdateRequest struct.
type InstallmentPlanUpdateRequest struct {
    RefOrderNumber       *string                `json:"RefOrderNumber,omitempty"`
    TrackingNumber       *string                `json:"TrackingNumber,omitempty"`
    Capture              *bool                  `json:"Capture,omitempty"`
    ShippingStatus       *ShippingStatusEnum    `json:"ShippingStatus,omitempty"`
    NewAmount            *string                `json:"NewAmount,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for InstallmentPlanUpdateRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstallmentPlanUpdateRequest) String() string {
    return fmt.Sprintf(
    	"InstallmentPlanUpdateRequest[RefOrderNumber=%v, TrackingNumber=%v, Capture=%v, ShippingStatus=%v, NewAmount=%v, AdditionalProperties=%v]",
    	i.RefOrderNumber, i.TrackingNumber, i.Capture, i.ShippingStatus, i.NewAmount, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for InstallmentPlanUpdateRequest.
// It customizes the JSON marshaling process for InstallmentPlanUpdateRequest objects.
func (i InstallmentPlanUpdateRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "RefOrderNumber", "TrackingNumber", "Capture", "ShippingStatus", "NewAmount"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the InstallmentPlanUpdateRequest object to a map representation for JSON marshaling.
func (i InstallmentPlanUpdateRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = i.RefOrderNumber
    }
    if i.TrackingNumber != nil {
        structMap["TrackingNumber"] = i.TrackingNumber
    }
    if i.Capture != nil {
        structMap["Capture"] = i.Capture
    }
    if i.ShippingStatus != nil {
        structMap["ShippingStatus"] = i.ShippingStatus
    }
    if i.NewAmount != nil {
        structMap["NewAmount"] = i.NewAmount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstallmentPlanUpdateRequest.
// It customizes the JSON unmarshaling process for InstallmentPlanUpdateRequest objects.
func (i *InstallmentPlanUpdateRequest) UnmarshalJSON(input []byte) error {
    var temp tempInstallmentPlanUpdateRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefOrderNumber", "TrackingNumber", "Capture", "ShippingStatus", "NewAmount")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.RefOrderNumber = temp.RefOrderNumber
    i.TrackingNumber = temp.TrackingNumber
    i.Capture = temp.Capture
    i.ShippingStatus = temp.ShippingStatus
    i.NewAmount = temp.NewAmount
    return nil
}

// tempInstallmentPlanUpdateRequest is a temporary struct used for validating the fields of InstallmentPlanUpdateRequest.
type tempInstallmentPlanUpdateRequest  struct {
    RefOrderNumber *string             `json:"RefOrderNumber,omitempty"`
    TrackingNumber *string             `json:"TrackingNumber,omitempty"`
    Capture        *bool               `json:"Capture,omitempty"`
    ShippingStatus *ShippingStatusEnum `json:"ShippingStatus,omitempty"`
    NewAmount      *string             `json:"NewAmount,omitempty"`
}
