// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// LinksData represents a LinksData struct.
type LinksData struct {
    Checkout             *string                `json:"Checkout,omitempty"`
    LearnMore            *string                `json:"LearnMore,omitempty"`
    TermsConditions      *string                `json:"TermsConditions,omitempty"`
    PrivacyPolicy        *string                `json:"PrivacyPolicy,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LinksData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LinksData) String() string {
    return fmt.Sprintf(
    	"LinksData[Checkout=%v, LearnMore=%v, TermsConditions=%v, PrivacyPolicy=%v, AdditionalProperties=%v]",
    	l.Checkout, l.LearnMore, l.TermsConditions, l.PrivacyPolicy, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LinksData.
// It customizes the JSON marshaling process for LinksData objects.
func (l LinksData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "Checkout", "LearnMore", "TermsConditions", "PrivacyPolicy"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LinksData object to a map representation for JSON marshaling.
func (l LinksData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    if l.Checkout != nil {
        structMap["Checkout"] = l.Checkout
    }
    if l.LearnMore != nil {
        structMap["LearnMore"] = l.LearnMore
    }
    if l.TermsConditions != nil {
        structMap["TermsConditions"] = l.TermsConditions
    }
    if l.PrivacyPolicy != nil {
        structMap["PrivacyPolicy"] = l.PrivacyPolicy
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LinksData.
// It customizes the JSON unmarshaling process for LinksData objects.
func (l *LinksData) UnmarshalJSON(input []byte) error {
    var temp tempLinksData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Checkout", "LearnMore", "TermsConditions", "PrivacyPolicy")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Checkout = temp.Checkout
    l.LearnMore = temp.LearnMore
    l.TermsConditions = temp.TermsConditions
    l.PrivacyPolicy = temp.PrivacyPolicy
    return nil
}

// tempLinksData is a temporary struct used for validating the fields of LinksData.
type tempLinksData  struct {
    Checkout        *string `json:"Checkout,omitempty"`
    LearnMore       *string `json:"LearnMore,omitempty"`
    TermsConditions *string `json:"TermsConditions,omitempty"`
    PrivacyPolicy   *string `json:"PrivacyPolicy,omitempty"`
}
