// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// LinksModel represents a LinksModel struct.
type LinksModel struct {
    PrivacyPolicyUrl      *string                `json:"PrivacyPolicyUrl,omitempty"`
    TermsAndConditionsUrl *string                `json:"TermsAndConditionsUrl,omitempty"`
    LearnMoreUrl          *string                `json:"LearnMoreUrl,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LinksModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LinksModel) String() string {
    return fmt.Sprintf(
    	"LinksModel[PrivacyPolicyUrl=%v, TermsAndConditionsUrl=%v, LearnMoreUrl=%v, AdditionalProperties=%v]",
    	l.PrivacyPolicyUrl, l.TermsAndConditionsUrl, l.LearnMoreUrl, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LinksModel.
// It customizes the JSON marshaling process for LinksModel objects.
func (l LinksModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "PrivacyPolicyUrl", "TermsAndConditionsUrl", "LearnMoreUrl"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LinksModel object to a map representation for JSON marshaling.
func (l LinksModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    if l.PrivacyPolicyUrl != nil {
        structMap["PrivacyPolicyUrl"] = l.PrivacyPolicyUrl
    }
    if l.TermsAndConditionsUrl != nil {
        structMap["TermsAndConditionsUrl"] = l.TermsAndConditionsUrl
    }
    if l.LearnMoreUrl != nil {
        structMap["LearnMoreUrl"] = l.LearnMoreUrl
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LinksModel.
// It customizes the JSON unmarshaling process for LinksModel objects.
func (l *LinksModel) UnmarshalJSON(input []byte) error {
    var temp tempLinksModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "PrivacyPolicyUrl", "TermsAndConditionsUrl", "LearnMoreUrl")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.PrivacyPolicyUrl = temp.PrivacyPolicyUrl
    l.TermsAndConditionsUrl = temp.TermsAndConditionsUrl
    l.LearnMoreUrl = temp.LearnMoreUrl
    return nil
}

// tempLinksModel is a temporary struct used for validating the fields of LinksModel.
type tempLinksModel  struct {
    PrivacyPolicyUrl      *string `json:"PrivacyPolicyUrl,omitempty"`
    TermsAndConditionsUrl *string `json:"TermsAndConditionsUrl,omitempty"`
    LearnMoreUrl          *string `json:"LearnMoreUrl,omitempty"`
}
