// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Error represents a Error struct.
type Error struct {
    Code                 *string                `json:"Code,omitempty"`
    Message              *string                `json:"Message,omitempty"`
    AdditionalInfo       *string                `json:"AdditionalInfo,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Error,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (m Error) String() string {
    return fmt.Sprintf(
    	"Error[Code=%v, Message=%v, AdditionalInfo=%v, AdditionalProperties=%v]",
    	m.Code, m.Message, m.AdditionalInfo, m.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Error.
// It customizes the JSON marshaling process for Error objects.
func (m Error) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(m.AdditionalProperties,
        "Code", "Message", "AdditionalInfo"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(m.toMap())
}

// toMap converts the Error object to a map representation for JSON marshaling.
func (m Error) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, m.AdditionalProperties)
    if m.Code != nil {
        structMap["Code"] = m.Code
    }
    if m.Message != nil {
        structMap["Message"] = m.Message
    }
    if m.AdditionalInfo != nil {
        structMap["AdditionalInfo"] = m.AdditionalInfo
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Error.
// It customizes the JSON unmarshaling process for Error objects.
func (m *Error) UnmarshalJSON(input []byte) error {
    var temp tempError
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Code", "Message", "AdditionalInfo")
    if err != nil {
    	return err
    }
    m.AdditionalProperties = additionalProperties
    
    m.Code = temp.Code
    m.Message = temp.Message
    m.AdditionalInfo = temp.AdditionalInfo
    return nil
}

// tempError is a temporary struct used for validating the fields of Error.
type tempError  struct {
    Code           *string `json:"Code,omitempty"`
    Message        *string `json:"Message,omitempty"`
    AdditionalInfo *string `json:"AdditionalInfo,omitempty"`
}
