// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// MockerShopperToken represents a MockerShopperToken struct.
type MockerShopperToken struct {
    Token                *string                `json:"Token,omitempty"`
    Last4Digit           *string                `json:"Last4Digit,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for MockerShopperToken,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (m MockerShopperToken) String() string {
    return fmt.Sprintf(
    	"MockerShopperToken[Token=%v, Last4Digit=%v, AdditionalProperties=%v]",
    	m.Token, m.Last4Digit, m.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for MockerShopperToken.
// It customizes the JSON marshaling process for MockerShopperToken objects.
func (m MockerShopperToken) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(m.AdditionalProperties,
        "Token", "Last4Digit"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(m.toMap())
}

// toMap converts the MockerShopperToken object to a map representation for JSON marshaling.
func (m MockerShopperToken) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, m.AdditionalProperties)
    if m.Token != nil {
        structMap["Token"] = m.Token
    }
    if m.Last4Digit != nil {
        structMap["Last4Digit"] = m.Last4Digit
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for MockerShopperToken.
// It customizes the JSON unmarshaling process for MockerShopperToken objects.
func (m *MockerShopperToken) UnmarshalJSON(input []byte) error {
    var temp tempMockerShopperToken
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Token", "Last4Digit")
    if err != nil {
    	return err
    }
    m.AdditionalProperties = additionalProperties
    
    m.Token = temp.Token
    m.Last4Digit = temp.Last4Digit
    return nil
}

// tempMockerShopperToken is a temporary struct used for validating the fields of MockerShopperToken.
type tempMockerShopperToken  struct {
    Token      *string `json:"Token,omitempty"`
    Last4Digit *string `json:"Last4Digit,omitempty"`
}
