// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// PaymentPlanOptionModel represents a PaymentPlanOptionModel struct.
type PaymentPlanOptionModel struct {
    NumberOfInstallments    int                    `json:"NumberOfInstallments"`
    FirstInstallmentAmount  float64                `json:"FirstInstallmentAmount"`
    InstallmentAmount       float64                `json:"InstallmentAmount"`
    LastInstallmentAmount   float64                `json:"LastInstallmentAmount"`
    Links                   *LinksModel            `json:"Links,omitempty"`
    TermsAndConditionsBrief *string                `json:"TermsAndConditionsBrief,omitempty"`
    InstallmentFrequency    *string                `json:"InstallmentFrequency,omitempty"`
    AdditionalProperties    map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for PaymentPlanOptionModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PaymentPlanOptionModel) String() string {
    return fmt.Sprintf(
    	"PaymentPlanOptionModel[NumberOfInstallments=%v, FirstInstallmentAmount=%v, InstallmentAmount=%v, LastInstallmentAmount=%v, Links=%v, TermsAndConditionsBrief=%v, InstallmentFrequency=%v, AdditionalProperties=%v]",
    	p.NumberOfInstallments, p.FirstInstallmentAmount, p.InstallmentAmount, p.LastInstallmentAmount, p.Links, p.TermsAndConditionsBrief, p.InstallmentFrequency, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for PaymentPlanOptionModel.
// It customizes the JSON marshaling process for PaymentPlanOptionModel objects.
func (p PaymentPlanOptionModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "NumberOfInstallments", "FirstInstallmentAmount", "InstallmentAmount", "LastInstallmentAmount", "Links", "TermsAndConditionsBrief", "InstallmentFrequency"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the PaymentPlanOptionModel object to a map representation for JSON marshaling.
func (p PaymentPlanOptionModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    structMap["NumberOfInstallments"] = p.NumberOfInstallments
    structMap["FirstInstallmentAmount"] = p.FirstInstallmentAmount
    structMap["InstallmentAmount"] = p.InstallmentAmount
    structMap["LastInstallmentAmount"] = p.LastInstallmentAmount
    if p.Links != nil {
        structMap["Links"] = p.Links.toMap()
    }
    if p.TermsAndConditionsBrief != nil {
        structMap["TermsAndConditionsBrief"] = p.TermsAndConditionsBrief
    }
    if p.InstallmentFrequency != nil {
        structMap["InstallmentFrequency"] = p.InstallmentFrequency
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for PaymentPlanOptionModel.
// It customizes the JSON unmarshaling process for PaymentPlanOptionModel objects.
func (p *PaymentPlanOptionModel) UnmarshalJSON(input []byte) error {
    var temp tempPaymentPlanOptionModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "NumberOfInstallments", "FirstInstallmentAmount", "InstallmentAmount", "LastInstallmentAmount", "Links", "TermsAndConditionsBrief", "InstallmentFrequency")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.NumberOfInstallments = *temp.NumberOfInstallments
    p.FirstInstallmentAmount = *temp.FirstInstallmentAmount
    p.InstallmentAmount = *temp.InstallmentAmount
    p.LastInstallmentAmount = *temp.LastInstallmentAmount
    p.Links = temp.Links
    p.TermsAndConditionsBrief = temp.TermsAndConditionsBrief
    p.InstallmentFrequency = temp.InstallmentFrequency
    return nil
}

// tempPaymentPlanOptionModel is a temporary struct used for validating the fields of PaymentPlanOptionModel.
type tempPaymentPlanOptionModel  struct {
    NumberOfInstallments    *int        `json:"NumberOfInstallments"`
    FirstInstallmentAmount  *float64    `json:"FirstInstallmentAmount"`
    InstallmentAmount       *float64    `json:"InstallmentAmount"`
    LastInstallmentAmount   *float64    `json:"LastInstallmentAmount"`
    Links                   *LinksModel `json:"Links,omitempty"`
    TermsAndConditionsBrief *string     `json:"TermsAndConditionsBrief,omitempty"`
    InstallmentFrequency    *string     `json:"InstallmentFrequency,omitempty"`
}

func (p *tempPaymentPlanOptionModel) validate() error {
    var errs []string
    if p.NumberOfInstallments == nil {
        errs = append(errs, "required field `NumberOfInstallments` is missing for type `PaymentPlanOptionModel`")
    }
    if p.FirstInstallmentAmount == nil {
        errs = append(errs, "required field `FirstInstallmentAmount` is missing for type `PaymentPlanOptionModel`")
    }
    if p.InstallmentAmount == nil {
        errs = append(errs, "required field `InstallmentAmount` is missing for type `PaymentPlanOptionModel`")
    }
    if p.LastInstallmentAmount == nil {
        errs = append(errs, "required field `LastInstallmentAmount` is missing for type `PaymentPlanOptionModel`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
