// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// PaymentMethodModel represents a PaymentMethodModel struct.
type PaymentMethodModel struct {
    Type                        PaymentMethodTypeEnum        `json:"Type"`
    Card                        *CardData                    `json:"Card,omitempty"`
    Token                       *string                      `json:"Token,omitempty"`
    BluesnapVaultedShopperToken *BluesnapVaultedShopperToken `json:"BluesnapVaultedShopperToken,omitempty"`
    MockerShopperToken          *MockerShopperToken          `json:"MockerShopperToken,omitempty"`
    SpreedlyToken               *SpreedlyToken               `json:"SpreedlyToken,omitempty"`
    CardPAR                     *string                      `json:"CardPAR,omitempty"`
    AdditionalProperties        map[string]interface{}       `json:"_"`
}

// String implements the fmt.Stringer interface for PaymentMethodModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PaymentMethodModel) String() string {
    return fmt.Sprintf(
    	"PaymentMethodModel[Type=%v, Card=%v, Token=%v, BluesnapVaultedShopperToken=%v, MockerShopperToken=%v, SpreedlyToken=%v, CardPAR=%v, AdditionalProperties=%v]",
    	p.Type, p.Card, p.Token, p.BluesnapVaultedShopperToken, p.MockerShopperToken, p.SpreedlyToken, p.CardPAR, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for PaymentMethodModel.
// It customizes the JSON marshaling process for PaymentMethodModel objects.
func (p PaymentMethodModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "Type", "Card", "Token", "BluesnapVaultedShopperToken", "MockerShopperToken", "SpreedlyToken", "CardPAR"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the PaymentMethodModel object to a map representation for JSON marshaling.
func (p PaymentMethodModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    structMap["Type"] = p.Type
    if p.Card != nil {
        structMap["Card"] = p.Card.toMap()
    }
    if p.Token != nil {
        structMap["Token"] = p.Token
    }
    if p.BluesnapVaultedShopperToken != nil {
        structMap["BluesnapVaultedShopperToken"] = p.BluesnapVaultedShopperToken.toMap()
    }
    if p.MockerShopperToken != nil {
        structMap["MockerShopperToken"] = p.MockerShopperToken.toMap()
    }
    if p.SpreedlyToken != nil {
        structMap["SpreedlyToken"] = p.SpreedlyToken.toMap()
    }
    if p.CardPAR != nil {
        structMap["CardPAR"] = p.CardPAR
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for PaymentMethodModel.
// It customizes the JSON unmarshaling process for PaymentMethodModel objects.
func (p *PaymentMethodModel) UnmarshalJSON(input []byte) error {
    var temp tempPaymentMethodModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Type", "Card", "Token", "BluesnapVaultedShopperToken", "MockerShopperToken", "SpreedlyToken", "CardPAR")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.Type = *temp.Type
    p.Card = temp.Card
    p.Token = temp.Token
    p.BluesnapVaultedShopperToken = temp.BluesnapVaultedShopperToken
    p.MockerShopperToken = temp.MockerShopperToken
    p.SpreedlyToken = temp.SpreedlyToken
    p.CardPAR = temp.CardPAR
    return nil
}

// tempPaymentMethodModel is a temporary struct used for validating the fields of PaymentMethodModel.
type tempPaymentMethodModel  struct {
    Type                        *PaymentMethodTypeEnum       `json:"Type"`
    Card                        *CardData                    `json:"Card,omitempty"`
    Token                       *string                      `json:"Token,omitempty"`
    BluesnapVaultedShopperToken *BluesnapVaultedShopperToken `json:"BluesnapVaultedShopperToken,omitempty"`
    MockerShopperToken          *MockerShopperToken          `json:"MockerShopperToken,omitempty"`
    SpreedlyToken               *SpreedlyToken               `json:"SpreedlyToken,omitempty"`
    CardPAR                     *string                      `json:"CardPAR,omitempty"`
}

func (p *tempPaymentMethodModel) validate() error {
    var errs []string
    if p.Type == nil {
        errs = append(errs, "required field `Type` is missing for type `PaymentMethodModel`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
