// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// PaymentInfo represents a PaymentInfo struct.
type PaymentInfo struct {
    CardBin              *string                `json:"CardBin,omitempty"`
    CardType             *CardTypeEnum          `json:"CardType,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for PaymentInfo,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PaymentInfo) String() string {
    return fmt.Sprintf(
    	"PaymentInfo[CardBin=%v, CardType=%v, AdditionalProperties=%v]",
    	p.CardBin, p.CardType, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for PaymentInfo.
// It customizes the JSON marshaling process for PaymentInfo objects.
func (p PaymentInfo) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "CardBin", "CardType"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the PaymentInfo object to a map representation for JSON marshaling.
func (p PaymentInfo) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    if p.CardBin != nil {
        structMap["CardBin"] = p.CardBin
    }
    if p.CardType != nil {
        structMap["CardType"] = p.CardType
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for PaymentInfo.
// It customizes the JSON unmarshaling process for PaymentInfo objects.
func (p *PaymentInfo) UnmarshalJSON(input []byte) error {
    var temp tempPaymentInfo
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "CardBin", "CardType")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.CardBin = temp.CardBin
    p.CardType = temp.CardType
    return nil
}

// tempPaymentInfo is a temporary struct used for validating the fields of PaymentInfo.
type tempPaymentInfo  struct {
    CardBin  *string       `json:"CardBin,omitempty"`
    CardType *CardTypeEnum `json:"CardType,omitempty"`
}
