// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// PlanDataModel represents a PlanDataModel struct.
type PlanDataModel struct {
    TotalAmount            string                 `json:"TotalAmount"`
    Currency               *string                `json:"Currency,omitempty"`
    NumberOfInstallments   Optional[int]          `json:"NumberOfInstallments"`
    TerminalId             *string                `json:"TerminalId,omitempty"`
    PurchaseMethod         PurchaseMethodEnum     `json:"PurchaseMethod"`
    RefOrderNumber         *string                `json:"RefOrderNumber,omitempty"`
    ExtendedParams         map[string]string      `json:"ExtendedParams,omitempty"`
    FirstInstallmentAmount *string                `json:"FirstInstallmentAmount,omitempty"`
    FirstInstallmentDate   *time.Time             `json:"FirstInstallmentDate,omitempty"`
    AdditionalProperties   map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for PlanDataModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PlanDataModel) String() string {
    return fmt.Sprintf(
    	"PlanDataModel[TotalAmount=%v, Currency=%v, NumberOfInstallments=%v, TerminalId=%v, PurchaseMethod=%v, RefOrderNumber=%v, ExtendedParams=%v, FirstInstallmentAmount=%v, FirstInstallmentDate=%v, AdditionalProperties=%v]",
    	p.TotalAmount, p.Currency, p.NumberOfInstallments, p.TerminalId, p.PurchaseMethod, p.RefOrderNumber, p.ExtendedParams, p.FirstInstallmentAmount, p.FirstInstallmentDate, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for PlanDataModel.
// It customizes the JSON marshaling process for PlanDataModel objects.
func (p PlanDataModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "TotalAmount", "Currency", "NumberOfInstallments", "TerminalId", "PurchaseMethod", "RefOrderNumber", "ExtendedParams", "FirstInstallmentAmount", "FirstInstallmentDate"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the PlanDataModel object to a map representation for JSON marshaling.
func (p PlanDataModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    structMap["TotalAmount"] = p.TotalAmount
    if p.Currency != nil {
        structMap["Currency"] = p.Currency
    }
    if p.NumberOfInstallments.IsValueSet() {
        if p.NumberOfInstallments.Value() != nil {
            structMap["NumberOfInstallments"] = p.NumberOfInstallments.Value()
        } else {
            structMap["NumberOfInstallments"] = nil
        }
    }
    if p.TerminalId != nil {
        structMap["TerminalId"] = p.TerminalId
    }
    structMap["PurchaseMethod"] = p.PurchaseMethod
    if p.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = p.RefOrderNumber
    }
    if p.ExtendedParams != nil {
        structMap["ExtendedParams"] = p.ExtendedParams
    }
    if p.FirstInstallmentAmount != nil {
        structMap["FirstInstallmentAmount"] = p.FirstInstallmentAmount
    }
    if p.FirstInstallmentDate != nil {
        structMap["FirstInstallmentDate"] = p.FirstInstallmentDate.Format(time.RFC3339)
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for PlanDataModel.
// It customizes the JSON unmarshaling process for PlanDataModel objects.
func (p *PlanDataModel) UnmarshalJSON(input []byte) error {
    var temp tempPlanDataModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "TotalAmount", "Currency", "NumberOfInstallments", "TerminalId", "PurchaseMethod", "RefOrderNumber", "ExtendedParams", "FirstInstallmentAmount", "FirstInstallmentDate")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.TotalAmount = *temp.TotalAmount
    p.Currency = temp.Currency
    p.NumberOfInstallments = temp.NumberOfInstallments
    p.TerminalId = temp.TerminalId
    p.PurchaseMethod = *temp.PurchaseMethod
    p.RefOrderNumber = temp.RefOrderNumber
    p.ExtendedParams = temp.ExtendedParams
    p.FirstInstallmentAmount = temp.FirstInstallmentAmount
    if temp.FirstInstallmentDate != nil {
        FirstInstallmentDateVal, err := time.Parse(time.RFC3339, *temp.FirstInstallmentDate)
        if err != nil {
            log.Fatalf("Cannot Parse FirstInstallmentDate as % s format.", time.RFC3339)
        }
        p.FirstInstallmentDate = &FirstInstallmentDateVal
    }
    return nil
}

// tempPlanDataModel is a temporary struct used for validating the fields of PlanDataModel.
type tempPlanDataModel  struct {
    TotalAmount            *string             `json:"TotalAmount"`
    Currency               *string             `json:"Currency,omitempty"`
    NumberOfInstallments   Optional[int]       `json:"NumberOfInstallments"`
    TerminalId             *string             `json:"TerminalId,omitempty"`
    PurchaseMethod         *PurchaseMethodEnum `json:"PurchaseMethod"`
    RefOrderNumber         *string             `json:"RefOrderNumber,omitempty"`
    ExtendedParams         map[string]string   `json:"ExtendedParams,omitempty"`
    FirstInstallmentAmount *string             `json:"FirstInstallmentAmount,omitempty"`
    FirstInstallmentDate   *string             `json:"FirstInstallmentDate,omitempty"`
}

func (p *tempPlanDataModel) validate() error {
    var errs []string
    if p.TotalAmount == nil {
        errs = append(errs, "required field `TotalAmount` is missing for type `PlanDataModel`")
    }
    if p.PurchaseMethod == nil {
        errs = append(errs, "required field `PurchaseMethod` is missing for type `PlanDataModel`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
