// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// PlanData represents a PlanData struct.
type PlanData struct {
    TerminalId                *string                `json:"TerminalId,omitempty"`
    TotalAmount               string                 `json:"TotalAmount"`
    FirstInstallmentAmount    *float64               `json:"FirstInstallmentAmount,omitempty"`
    Currency                  *string                `json:"Currency,omitempty"`
    NumberOfInstallments      int                    `json:"NumberOfInstallments"`
    PurchaseMethod            PurchaseMethodEnum     `json:"PurchaseMethod"`
    RefOrderNumber            *string                `json:"RefOrderNumber,omitempty"`
    AllowedInstallmentOptions []int                  `json:"AllowedInstallmentOptions,omitempty"`
    Tags                      map[string]string      `json:"Tags,omitempty"`
    ProcessingData            *ProcessingData        `json:"ProcessingData,omitempty"`
    FirstInstallmentDate      *time.Time             `json:"FirstInstallmentDate,omitempty"`
    AdditionalProperties      map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for PlanData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p PlanData) String() string {
    return fmt.Sprintf(
    	"PlanData[TerminalId=%v, TotalAmount=%v, FirstInstallmentAmount=%v, Currency=%v, NumberOfInstallments=%v, PurchaseMethod=%v, RefOrderNumber=%v, AllowedInstallmentOptions=%v, Tags=%v, ProcessingData=%v, FirstInstallmentDate=%v, AdditionalProperties=%v]",
    	p.TerminalId, p.TotalAmount, p.FirstInstallmentAmount, p.Currency, p.NumberOfInstallments, p.PurchaseMethod, p.RefOrderNumber, p.AllowedInstallmentOptions, p.Tags, p.ProcessingData, p.FirstInstallmentDate, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for PlanData.
// It customizes the JSON marshaling process for PlanData objects.
func (p PlanData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "TerminalId", "TotalAmount", "FirstInstallmentAmount", "Currency", "NumberOfInstallments", "PurchaseMethod", "RefOrderNumber", "AllowedInstallmentOptions", "Tags", "ProcessingData", "FirstInstallmentDate"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the PlanData object to a map representation for JSON marshaling.
func (p PlanData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    if p.TerminalId != nil {
        structMap["TerminalId"] = p.TerminalId
    }
    structMap["TotalAmount"] = p.TotalAmount
    if p.FirstInstallmentAmount != nil {
        structMap["FirstInstallmentAmount"] = p.FirstInstallmentAmount
    }
    if p.Currency != nil {
        structMap["Currency"] = p.Currency
    }
    structMap["NumberOfInstallments"] = p.NumberOfInstallments
    structMap["PurchaseMethod"] = p.PurchaseMethod
    if p.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = p.RefOrderNumber
    }
    if p.AllowedInstallmentOptions != nil {
        structMap["AllowedInstallmentOptions"] = p.AllowedInstallmentOptions
    }
    if p.Tags != nil {
        structMap["Tags"] = p.Tags
    }
    if p.ProcessingData != nil {
        structMap["ProcessingData"] = p.ProcessingData.toMap()
    }
    if p.FirstInstallmentDate != nil {
        structMap["FirstInstallmentDate"] = p.FirstInstallmentDate.Format(time.RFC3339)
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for PlanData.
// It customizes the JSON unmarshaling process for PlanData objects.
func (p *PlanData) UnmarshalJSON(input []byte) error {
    var temp tempPlanData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "TerminalId", "TotalAmount", "FirstInstallmentAmount", "Currency", "NumberOfInstallments", "PurchaseMethod", "RefOrderNumber", "AllowedInstallmentOptions", "Tags", "ProcessingData", "FirstInstallmentDate")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.TerminalId = temp.TerminalId
    p.TotalAmount = *temp.TotalAmount
    p.FirstInstallmentAmount = temp.FirstInstallmentAmount
    p.Currency = temp.Currency
    p.NumberOfInstallments = *temp.NumberOfInstallments
    p.PurchaseMethod = *temp.PurchaseMethod
    p.RefOrderNumber = temp.RefOrderNumber
    p.AllowedInstallmentOptions = temp.AllowedInstallmentOptions
    p.Tags = temp.Tags
    p.ProcessingData = temp.ProcessingData
    if temp.FirstInstallmentDate != nil {
        FirstInstallmentDateVal, err := time.Parse(time.RFC3339, *temp.FirstInstallmentDate)
        if err != nil {
            log.Fatalf("Cannot Parse FirstInstallmentDate as % s format.", time.RFC3339)
        }
        p.FirstInstallmentDate = &FirstInstallmentDateVal
    }
    return nil
}

// tempPlanData is a temporary struct used for validating the fields of PlanData.
type tempPlanData  struct {
    TerminalId                *string             `json:"TerminalId,omitempty"`
    TotalAmount               *string             `json:"TotalAmount"`
    FirstInstallmentAmount    *float64            `json:"FirstInstallmentAmount,omitempty"`
    Currency                  *string             `json:"Currency,omitempty"`
    NumberOfInstallments      *int                `json:"NumberOfInstallments"`
    PurchaseMethod            *PurchaseMethodEnum `json:"PurchaseMethod"`
    RefOrderNumber            *string             `json:"RefOrderNumber,omitempty"`
    AllowedInstallmentOptions []int               `json:"AllowedInstallmentOptions,omitempty"`
    Tags                      map[string]string   `json:"Tags,omitempty"`
    ProcessingData            *ProcessingData     `json:"ProcessingData,omitempty"`
    FirstInstallmentDate      *string             `json:"FirstInstallmentDate,omitempty"`
}

func (p *tempPlanData) validate() error {
    var errs []string
    if p.TotalAmount == nil {
        errs = append(errs, "required field `TotalAmount` is missing for type `PlanData`")
    }
    if p.NumberOfInstallments == nil {
        errs = append(errs, "required field `NumberOfInstallments` is missing for type `PlanData`")
    }
    if p.PurchaseMethod == nil {
        errs = append(errs, "required field `PurchaseMethod` is missing for type `PlanData`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
