// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ProcessingData represents a ProcessingData struct.
type ProcessingData struct {
    AttemptThreeDSecured *bool                  `json:"AttemptThreeDSecured,omitempty"`
    SoftDescriptor       *string                `json:"SoftDescriptor,omitempty"`
    ThreeDSData          *ThreeDSData           `json:"ThreeDSData,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ProcessingData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (p ProcessingData) String() string {
    return fmt.Sprintf(
    	"ProcessingData[AttemptThreeDSecured=%v, SoftDescriptor=%v, ThreeDSData=%v, AdditionalProperties=%v]",
    	p.AttemptThreeDSecured, p.SoftDescriptor, p.ThreeDSData, p.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ProcessingData.
// It customizes the JSON marshaling process for ProcessingData objects.
func (p ProcessingData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(p.AdditionalProperties,
        "AttemptThreeDSecured", "SoftDescriptor", "ThreeDSData"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(p.toMap())
}

// toMap converts the ProcessingData object to a map representation for JSON marshaling.
func (p ProcessingData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, p.AdditionalProperties)
    if p.AttemptThreeDSecured != nil {
        structMap["AttemptThreeDSecured"] = p.AttemptThreeDSecured
    }
    if p.SoftDescriptor != nil {
        structMap["SoftDescriptor"] = p.SoftDescriptor
    }
    if p.ThreeDSData != nil {
        structMap["ThreeDSData"] = p.ThreeDSData.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProcessingData.
// It customizes the JSON unmarshaling process for ProcessingData objects.
func (p *ProcessingData) UnmarshalJSON(input []byte) error {
    var temp tempProcessingData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "AttemptThreeDSecured", "SoftDescriptor", "ThreeDSData")
    if err != nil {
    	return err
    }
    p.AdditionalProperties = additionalProperties
    
    p.AttemptThreeDSecured = temp.AttemptThreeDSecured
    p.SoftDescriptor = temp.SoftDescriptor
    p.ThreeDSData = temp.ThreeDSData
    return nil
}

// tempProcessingData is a temporary struct used for validating the fields of ProcessingData.
type tempProcessingData  struct {
    AttemptThreeDSecured *bool        `json:"AttemptThreeDSecured,omitempty"`
    SoftDescriptor       *string      `json:"SoftDescriptor,omitempty"`
    ThreeDSData          *ThreeDSData `json:"ThreeDSData,omitempty"`
}
