// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// RedirectionEndpointsModel represents a RedirectionEndpointsModel struct.
type RedirectionEndpointsModel struct {
    AuthorizeSucceeded   *string                `json:"AuthorizeSucceeded,omitempty"`
    Succeeded            *string                `json:"Succeeded,omitempty"`
    AuthorizeFailed      *string                `json:"AuthorizeFailed,omitempty"`
    Failed               *string                `json:"Failed,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for RedirectionEndpointsModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r RedirectionEndpointsModel) String() string {
    return fmt.Sprintf(
    	"RedirectionEndpointsModel[AuthorizeSucceeded=%v, Succeeded=%v, AuthorizeFailed=%v, Failed=%v, AdditionalProperties=%v]",
    	r.AuthorizeSucceeded, r.Succeeded, r.AuthorizeFailed, r.Failed, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for RedirectionEndpointsModel.
// It customizes the JSON marshaling process for RedirectionEndpointsModel objects.
func (r RedirectionEndpointsModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "AuthorizeSucceeded", "Succeeded", "AuthorizeFailed", "Failed"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the RedirectionEndpointsModel object to a map representation for JSON marshaling.
func (r RedirectionEndpointsModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    if r.AuthorizeSucceeded != nil {
        structMap["AuthorizeSucceeded"] = r.AuthorizeSucceeded
    }
    if r.Succeeded != nil {
        structMap["Succeeded"] = r.Succeeded
    }
    if r.AuthorizeFailed != nil {
        structMap["AuthorizeFailed"] = r.AuthorizeFailed
    }
    if r.Failed != nil {
        structMap["Failed"] = r.Failed
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for RedirectionEndpointsModel.
// It customizes the JSON unmarshaling process for RedirectionEndpointsModel objects.
func (r *RedirectionEndpointsModel) UnmarshalJSON(input []byte) error {
    var temp tempRedirectionEndpointsModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "AuthorizeSucceeded", "Succeeded", "AuthorizeFailed", "Failed")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.AuthorizeSucceeded = temp.AuthorizeSucceeded
    r.Succeeded = temp.Succeeded
    r.AuthorizeFailed = temp.AuthorizeFailed
    r.Failed = temp.Failed
    return nil
}

// tempRedirectionEndpointsModel is a temporary struct used for validating the fields of RedirectionEndpointsModel.
type tempRedirectionEndpointsModel  struct {
    AuthorizeSucceeded *string `json:"AuthorizeSucceeded,omitempty"`
    Succeeded          *string `json:"Succeeded,omitempty"`
    AuthorizeFailed    *string `json:"AuthorizeFailed,omitempty"`
    Failed             *string `json:"Failed,omitempty"`
}
