// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// RefundSummary represents a RefundSummary struct.
type RefundSummary struct {
    TotalAmount          *float64               `json:"TotalAmount,omitempty"`
    FailedAmount         *float64               `json:"FailedAmount,omitempty"`
    SucceededAmount      *float64               `json:"SucceededAmount,omitempty"`
    PendingAmount        *float64               `json:"PendingAmount,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for RefundSummary,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r RefundSummary) String() string {
    return fmt.Sprintf(
    	"RefundSummary[TotalAmount=%v, FailedAmount=%v, SucceededAmount=%v, PendingAmount=%v, AdditionalProperties=%v]",
    	r.TotalAmount, r.FailedAmount, r.SucceededAmount, r.PendingAmount, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for RefundSummary.
// It customizes the JSON marshaling process for RefundSummary objects.
func (r RefundSummary) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "TotalAmount", "FailedAmount", "SucceededAmount", "PendingAmount"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the RefundSummary object to a map representation for JSON marshaling.
func (r RefundSummary) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    if r.TotalAmount != nil {
        structMap["TotalAmount"] = r.TotalAmount
    }
    if r.FailedAmount != nil {
        structMap["FailedAmount"] = r.FailedAmount
    }
    if r.SucceededAmount != nil {
        structMap["SucceededAmount"] = r.SucceededAmount
    }
    if r.PendingAmount != nil {
        structMap["PendingAmount"] = r.PendingAmount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for RefundSummary.
// It customizes the JSON unmarshaling process for RefundSummary objects.
func (r *RefundSummary) UnmarshalJSON(input []byte) error {
    var temp tempRefundSummary
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "TotalAmount", "FailedAmount", "SucceededAmount", "PendingAmount")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.TotalAmount = temp.TotalAmount
    r.FailedAmount = temp.FailedAmount
    r.SucceededAmount = temp.SucceededAmount
    r.PendingAmount = temp.PendingAmount
    return nil
}

// tempRefundSummary is a temporary struct used for validating the fields of RefundSummary.
type tempRefundSummary  struct {
    TotalAmount     *float64 `json:"TotalAmount,omitempty"`
    FailedAmount    *float64 `json:"FailedAmount,omitempty"`
    SucceededAmount *float64 `json:"SucceededAmount,omitempty"`
    PendingAmount   *float64 `json:"PendingAmount,omitempty"`
}
