// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// RefundModel represents a RefundModel struct.
type RefundModel struct {
    RefundId              *string                `json:"RefundId,omitempty"`
    SubmitDate            time.Time              `json:"SubmitDate"`
    TotalAmount           float64                `json:"TotalAmount"`
    Status                RefundStatusEnum       `json:"Status"`
    NonCreditRefundAmount float64                `json:"NonCreditRefundAmount"`
    CreditRefundAmount    float64                `json:"CreditRefundAmount"`
    ReferenceId           *string                `json:"ReferenceId,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for RefundModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r RefundModel) String() string {
    return fmt.Sprintf(
    	"RefundModel[RefundId=%v, SubmitDate=%v, TotalAmount=%v, Status=%v, NonCreditRefundAmount=%v, CreditRefundAmount=%v, ReferenceId=%v, AdditionalProperties=%v]",
    	r.RefundId, r.SubmitDate, r.TotalAmount, r.Status, r.NonCreditRefundAmount, r.CreditRefundAmount, r.ReferenceId, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for RefundModel.
// It customizes the JSON marshaling process for RefundModel objects.
func (r RefundModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "RefundId", "SubmitDate", "TotalAmount", "Status", "NonCreditRefundAmount", "CreditRefundAmount", "ReferenceId"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the RefundModel object to a map representation for JSON marshaling.
func (r RefundModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    if r.RefundId != nil {
        structMap["RefundId"] = r.RefundId
    }
    structMap["SubmitDate"] = r.SubmitDate.Format(time.RFC3339)
    structMap["TotalAmount"] = r.TotalAmount
    structMap["Status"] = r.Status
    structMap["NonCreditRefundAmount"] = r.NonCreditRefundAmount
    structMap["CreditRefundAmount"] = r.CreditRefundAmount
    if r.ReferenceId != nil {
        structMap["ReferenceId"] = r.ReferenceId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for RefundModel.
// It customizes the JSON unmarshaling process for RefundModel objects.
func (r *RefundModel) UnmarshalJSON(input []byte) error {
    var temp tempRefundModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "RefundId", "SubmitDate", "TotalAmount", "Status", "NonCreditRefundAmount", "CreditRefundAmount", "ReferenceId")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.RefundId = temp.RefundId
    SubmitDateVal, err := time.Parse(time.RFC3339, *temp.SubmitDate)
    if err != nil {
        log.Fatalf("Cannot Parse SubmitDate as % s format.", time.RFC3339)
    }
    r.SubmitDate = SubmitDateVal
    r.TotalAmount = *temp.TotalAmount
    r.Status = *temp.Status
    r.NonCreditRefundAmount = *temp.NonCreditRefundAmount
    r.CreditRefundAmount = *temp.CreditRefundAmount
    r.ReferenceId = temp.ReferenceId
    return nil
}

// tempRefundModel is a temporary struct used for validating the fields of RefundModel.
type tempRefundModel  struct {
    RefundId              *string           `json:"RefundId,omitempty"`
    SubmitDate            *string           `json:"SubmitDate"`
    TotalAmount           *float64          `json:"TotalAmount"`
    Status                *RefundStatusEnum `json:"Status"`
    NonCreditRefundAmount *float64          `json:"NonCreditRefundAmount"`
    CreditRefundAmount    *float64          `json:"CreditRefundAmount"`
    ReferenceId           *string           `json:"ReferenceId,omitempty"`
}

func (r *tempRefundModel) validate() error {
    var errs []string
    if r.SubmitDate == nil {
        errs = append(errs, "required field `SubmitDate` is missing for type `RefundModel`")
    }
    if r.TotalAmount == nil {
        errs = append(errs, "required field `TotalAmount` is missing for type `RefundModel`")
    }
    if r.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `RefundModel`")
    }
    if r.NonCreditRefundAmount == nil {
        errs = append(errs, "required field `NonCreditRefundAmount` is missing for type `RefundModel`")
    }
    if r.CreditRefundAmount == nil {
        errs = append(errs, "required field `CreditRefundAmount` is missing for type `RefundModel`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
