// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// SearchInstallmentPlanResponseItem represents a SearchInstallmentPlanResponseItem struct.
type SearchInstallmentPlanResponseItem struct {
    InstallmentPlanNumber *string                `json:"InstallmentPlanNumber,omitempty"`
    DateCreated           time.Time              `json:"DateCreated"`
    RefOrderNumber        *string                `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum    `json:"PurchaseMethod,omitempty"`
    Status                PlanStatusEnum         `json:"Status"`
    Currency              *string                `json:"Currency,omitempty"`
    OriginalAmount        *float64               `json:"OriginalAmount,omitempty"`
    Amount                *float64               `json:"Amount,omitempty"`
    Authorization         *AuthorizationModel    `json:"Authorization,omitempty"`
    Shopper               *ShopperData           `json:"Shopper,omitempty"`
    BillingAddress        *AddressData           `json:"BillingAddress,omitempty"`
    PaymentMethod         *PaymentMethodModel    `json:"PaymentMethod,omitempty"`
    ExtendedParams        map[string]string      `json:"ExtendedParams,omitempty"`
    Installments          []Installment          `json:"Installments,omitempty"`
    Refunds               []RefundModel          `json:"Refunds,omitempty"`
    Links                 *LinksData             `json:"Links,omitempty"`
    AdditionalProperties  map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for SearchInstallmentPlanResponseItem,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchInstallmentPlanResponseItem) String() string {
    return fmt.Sprintf(
    	"SearchInstallmentPlanResponseItem[InstallmentPlanNumber=%v, DateCreated=%v, RefOrderNumber=%v, PurchaseMethod=%v, Status=%v, Currency=%v, OriginalAmount=%v, Amount=%v, Authorization=%v, Shopper=%v, BillingAddress=%v, PaymentMethod=%v, ExtendedParams=%v, Installments=%v, Refunds=%v, Links=%v, AdditionalProperties=%v]",
    	s.InstallmentPlanNumber, s.DateCreated, s.RefOrderNumber, s.PurchaseMethod, s.Status, s.Currency, s.OriginalAmount, s.Amount, s.Authorization, s.Shopper, s.BillingAddress, s.PaymentMethod, s.ExtendedParams, s.Installments, s.Refunds, s.Links, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SearchInstallmentPlanResponseItem.
// It customizes the JSON marshaling process for SearchInstallmentPlanResponseItem objects.
func (s SearchInstallmentPlanResponseItem) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "InstallmentPlanNumber", "DateCreated", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "OriginalAmount", "Amount", "Authorization", "Shopper", "BillingAddress", "PaymentMethod", "ExtendedParams", "Installments", "Refunds", "Links"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchInstallmentPlanResponseItem object to a map representation for JSON marshaling.
func (s SearchInstallmentPlanResponseItem) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.InstallmentPlanNumber != nil {
        structMap["InstallmentPlanNumber"] = s.InstallmentPlanNumber
    }
    structMap["DateCreated"] = s.DateCreated.Format(time.RFC3339)
    if s.RefOrderNumber != nil {
        structMap["RefOrderNumber"] = s.RefOrderNumber
    }
    if s.PurchaseMethod != nil {
        structMap["PurchaseMethod"] = s.PurchaseMethod
    }
    structMap["Status"] = s.Status
    if s.Currency != nil {
        structMap["Currency"] = s.Currency
    }
    if s.OriginalAmount != nil {
        structMap["OriginalAmount"] = s.OriginalAmount
    }
    if s.Amount != nil {
        structMap["Amount"] = s.Amount
    }
    if s.Authorization != nil {
        structMap["Authorization"] = s.Authorization.toMap()
    }
    if s.Shopper != nil {
        structMap["Shopper"] = s.Shopper.toMap()
    }
    if s.BillingAddress != nil {
        structMap["BillingAddress"] = s.BillingAddress.toMap()
    }
    if s.PaymentMethod != nil {
        structMap["PaymentMethod"] = s.PaymentMethod.toMap()
    }
    if s.ExtendedParams != nil {
        structMap["ExtendedParams"] = s.ExtendedParams
    }
    if s.Installments != nil {
        structMap["Installments"] = s.Installments
    }
    if s.Refunds != nil {
        structMap["Refunds"] = s.Refunds
    }
    if s.Links != nil {
        structMap["Links"] = s.Links.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchInstallmentPlanResponseItem.
// It customizes the JSON unmarshaling process for SearchInstallmentPlanResponseItem objects.
func (s *SearchInstallmentPlanResponseItem) UnmarshalJSON(input []byte) error {
    var temp tempSearchInstallmentPlanResponseItem
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "InstallmentPlanNumber", "DateCreated", "RefOrderNumber", "PurchaseMethod", "Status", "Currency", "OriginalAmount", "Amount", "Authorization", "Shopper", "BillingAddress", "PaymentMethod", "ExtendedParams", "Installments", "Refunds", "Links")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.InstallmentPlanNumber = temp.InstallmentPlanNumber
    DateCreatedVal, err := time.Parse(time.RFC3339, *temp.DateCreated)
    if err != nil {
        log.Fatalf("Cannot Parse DateCreated as % s format.", time.RFC3339)
    }
    s.DateCreated = DateCreatedVal
    s.RefOrderNumber = temp.RefOrderNumber
    s.PurchaseMethod = temp.PurchaseMethod
    s.Status = *temp.Status
    s.Currency = temp.Currency
    s.OriginalAmount = temp.OriginalAmount
    s.Amount = temp.Amount
    s.Authorization = temp.Authorization
    s.Shopper = temp.Shopper
    s.BillingAddress = temp.BillingAddress
    s.PaymentMethod = temp.PaymentMethod
    s.ExtendedParams = temp.ExtendedParams
    s.Installments = temp.Installments
    s.Refunds = temp.Refunds
    s.Links = temp.Links
    return nil
}

// tempSearchInstallmentPlanResponseItem is a temporary struct used for validating the fields of SearchInstallmentPlanResponseItem.
type tempSearchInstallmentPlanResponseItem  struct {
    InstallmentPlanNumber *string             `json:"InstallmentPlanNumber,omitempty"`
    DateCreated           *string             `json:"DateCreated"`
    RefOrderNumber        *string             `json:"RefOrderNumber,omitempty"`
    PurchaseMethod        *PurchaseMethodEnum `json:"PurchaseMethod,omitempty"`
    Status                *PlanStatusEnum     `json:"Status"`
    Currency              *string             `json:"Currency,omitempty"`
    OriginalAmount        *float64            `json:"OriginalAmount,omitempty"`
    Amount                *float64            `json:"Amount,omitempty"`
    Authorization         *AuthorizationModel `json:"Authorization,omitempty"`
    Shopper               *ShopperData        `json:"Shopper,omitempty"`
    BillingAddress        *AddressData        `json:"BillingAddress,omitempty"`
    PaymentMethod         *PaymentMethodModel `json:"PaymentMethod,omitempty"`
    ExtendedParams        map[string]string   `json:"ExtendedParams,omitempty"`
    Installments          []Installment       `json:"Installments,omitempty"`
    Refunds               []RefundModel       `json:"Refunds,omitempty"`
    Links                 *LinksData          `json:"Links,omitempty"`
}

func (s *tempSearchInstallmentPlanResponseItem) validate() error {
    var errs []string
    if s.DateCreated == nil {
        errs = append(errs, "required field `DateCreated` is missing for type `SearchInstallmentPlanResponseItem`")
    }
    if s.Status == nil {
        errs = append(errs, "required field `Status` is missing for type `SearchInstallmentPlanResponseItem`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
