// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ShopperData represents a ShopperData struct.
type ShopperData struct {
    FullName             *string                `json:"FullName,omitempty"`
    Email                *string                `json:"Email,omitempty"`
    PhoneNumber          *string                `json:"PhoneNumber,omitempty"`
    Culture              *string                `json:"Culture,omitempty"`
    ExternalId           *string                `json:"ExternalId,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ShopperData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s ShopperData) String() string {
    return fmt.Sprintf(
    	"ShopperData[FullName=%v, Email=%v, PhoneNumber=%v, Culture=%v, ExternalId=%v, AdditionalProperties=%v]",
    	s.FullName, s.Email, s.PhoneNumber, s.Culture, s.ExternalId, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ShopperData.
// It customizes the JSON marshaling process for ShopperData objects.
func (s ShopperData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "FullName", "Email", "PhoneNumber", "Culture", "ExternalId"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the ShopperData object to a map representation for JSON marshaling.
func (s ShopperData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.FullName != nil {
        structMap["FullName"] = s.FullName
    }
    if s.Email != nil {
        structMap["Email"] = s.Email
    }
    if s.PhoneNumber != nil {
        structMap["PhoneNumber"] = s.PhoneNumber
    }
    if s.Culture != nil {
        structMap["Culture"] = s.Culture
    }
    if s.ExternalId != nil {
        structMap["ExternalId"] = s.ExternalId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShopperData.
// It customizes the JSON unmarshaling process for ShopperData objects.
func (s *ShopperData) UnmarshalJSON(input []byte) error {
    var temp tempShopperData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "FullName", "Email", "PhoneNumber", "Culture", "ExternalId")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.FullName = temp.FullName
    s.Email = temp.Email
    s.PhoneNumber = temp.PhoneNumber
    s.Culture = temp.Culture
    s.ExternalId = temp.ExternalId
    return nil
}

// tempShopperData is a temporary struct used for validating the fields of ShopperData.
type tempShopperData  struct {
    FullName    *string `json:"FullName,omitempty"`
    Email       *string `json:"Email,omitempty"`
    PhoneNumber *string `json:"PhoneNumber,omitempty"`
    Culture     *string `json:"Culture,omitempty"`
    ExternalId  *string `json:"ExternalId,omitempty"`
}
