// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// SpreedlyToken represents a SpreedlyToken struct.
type SpreedlyToken struct {
    Token                *string                `json:"Token,omitempty"`
    Last4Digit           *string                `json:"Last4Digit,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for SpreedlyToken,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SpreedlyToken) String() string {
    return fmt.Sprintf(
    	"SpreedlyToken[Token=%v, Last4Digit=%v, AdditionalProperties=%v]",
    	s.Token, s.Last4Digit, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SpreedlyToken.
// It customizes the JSON marshaling process for SpreedlyToken objects.
func (s SpreedlyToken) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "Token", "Last4Digit"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SpreedlyToken object to a map representation for JSON marshaling.
func (s SpreedlyToken) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Token != nil {
        structMap["Token"] = s.Token
    }
    if s.Last4Digit != nil {
        structMap["Last4Digit"] = s.Last4Digit
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SpreedlyToken.
// It customizes the JSON unmarshaling process for SpreedlyToken objects.
func (s *SpreedlyToken) UnmarshalJSON(input []byte) error {
    var temp tempSpreedlyToken
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Token", "Last4Digit")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Token = temp.Token
    s.Last4Digit = temp.Last4Digit
    return nil
}

// tempSpreedlyToken is a temporary struct used for validating the fields of SpreedlyToken.
type tempSpreedlyToken  struct {
    Token      *string `json:"Token,omitempty"`
    Last4Digit *string `json:"Last4Digit,omitempty"`
}
