// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ThreeDsRedirectDataV3 represents a ThreeDsRedirectDataV3 struct.
type ThreeDsRedirectDataV3 struct {
    Url                  *string                `json:"Url,omitempty"`
    Verb                 *string                `json:"Verb,omitempty"`
    Params               map[string]string      `json:"Params,omitempty"`
    ClientRedirectUrl    *string                `json:"ClientRedirectUrl,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ThreeDsRedirectDataV3,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t ThreeDsRedirectDataV3) String() string {
    return fmt.Sprintf(
    	"ThreeDsRedirectDataV3[Url=%v, Verb=%v, Params=%v, ClientRedirectUrl=%v, AdditionalProperties=%v]",
    	t.Url, t.Verb, t.Params, t.ClientRedirectUrl, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ThreeDsRedirectDataV3.
// It customizes the JSON marshaling process for ThreeDsRedirectDataV3 objects.
func (t ThreeDsRedirectDataV3) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "Url", "Verb", "Params", "ClientRedirectUrl"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the ThreeDsRedirectDataV3 object to a map representation for JSON marshaling.
func (t ThreeDsRedirectDataV3) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    if t.Url != nil {
        structMap["Url"] = t.Url
    }
    if t.Verb != nil {
        structMap["Verb"] = t.Verb
    }
    if t.Params != nil {
        structMap["Params"] = t.Params
    }
    if t.ClientRedirectUrl != nil {
        structMap["ClientRedirectUrl"] = t.ClientRedirectUrl
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ThreeDsRedirectDataV3.
// It customizes the JSON unmarshaling process for ThreeDsRedirectDataV3 objects.
func (t *ThreeDsRedirectDataV3) UnmarshalJSON(input []byte) error {
    var temp tempThreeDsRedirectDataV3
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "Url", "Verb", "Params", "ClientRedirectUrl")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.Url = temp.Url
    t.Verb = temp.Verb
    t.Params = temp.Params
    t.ClientRedirectUrl = temp.ClientRedirectUrl
    return nil
}

// tempThreeDsRedirectDataV3 is a temporary struct used for validating the fields of ThreeDsRedirectDataV3.
type tempThreeDsRedirectDataV3  struct {
    Url               *string           `json:"Url,omitempty"`
    Verb              *string           `json:"Verb,omitempty"`
    Params            map[string]string `json:"Params,omitempty"`
    ClientRedirectUrl *string           `json:"ClientRedirectUrl,omitempty"`
}
