// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ThreeDSData represents a ThreeDSData struct.
type ThreeDSData struct {
    ECI                  *string                `json:"ECI,omitempty"`
    CAVV                 *string                `json:"CAVV,omitempty"`
    XID                  *string                `json:"XID,omitempty"`
    DirectoryServerTxnId *string                `json:"DirectoryServerTxnId,omitempty"`
    ThreeDSVersion       *string                `json:"ThreeDSVersion,omitempty"`
    TransactionId        *string                `json:"TransactionId,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ThreeDSData,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t ThreeDSData) String() string {
    return fmt.Sprintf(
    	"ThreeDSData[ECI=%v, CAVV=%v, XID=%v, DirectoryServerTxnId=%v, ThreeDSVersion=%v, TransactionId=%v, AdditionalProperties=%v]",
    	t.ECI, t.CAVV, t.XID, t.DirectoryServerTxnId, t.ThreeDSVersion, t.TransactionId, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ThreeDSData.
// It customizes the JSON marshaling process for ThreeDSData objects.
func (t ThreeDSData) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "ECI", "CAVV", "XID", "DirectoryServerTxnId", "ThreeDSVersion", "TransactionId"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the ThreeDSData object to a map representation for JSON marshaling.
func (t ThreeDSData) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    if t.ECI != nil {
        structMap["ECI"] = t.ECI
    }
    if t.CAVV != nil {
        structMap["CAVV"] = t.CAVV
    }
    if t.XID != nil {
        structMap["XID"] = t.XID
    }
    if t.DirectoryServerTxnId != nil {
        structMap["DirectoryServerTxnId"] = t.DirectoryServerTxnId
    }
    if t.ThreeDSVersion != nil {
        structMap["ThreeDSVersion"] = t.ThreeDSVersion
    }
    if t.TransactionId != nil {
        structMap["TransactionId"] = t.TransactionId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ThreeDSData.
// It customizes the JSON unmarshaling process for ThreeDSData objects.
func (t *ThreeDSData) UnmarshalJSON(input []byte) error {
    var temp tempThreeDSData
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "ECI", "CAVV", "XID", "DirectoryServerTxnId", "ThreeDSVersion", "TransactionId")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.ECI = temp.ECI
    t.CAVV = temp.CAVV
    t.XID = temp.XID
    t.DirectoryServerTxnId = temp.DirectoryServerTxnId
    t.ThreeDSVersion = temp.ThreeDSVersion
    t.TransactionId = temp.TransactionId
    return nil
}

// tempThreeDSData is a temporary struct used for validating the fields of ThreeDSData.
type tempThreeDSData  struct {
    ECI                  *string `json:"ECI,omitempty"`
    CAVV                 *string `json:"CAVV,omitempty"`
    XID                  *string `json:"XID,omitempty"`
    DirectoryServerTxnId *string `json:"DirectoryServerTxnId,omitempty"`
    ThreeDSVersion       *string `json:"ThreeDSVersion,omitempty"`
    TransactionId        *string `json:"TransactionId,omitempty"`
}
