// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// UxSettingsModel represents a UxSettingsModel struct.
type UxSettingsModel struct {
    DisplayedInstallmentOptions []int                  `json:"DisplayedInstallmentOptions,omitempty"`
    AdditionalProperties        map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for UxSettingsModel,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (u UxSettingsModel) String() string {
    return fmt.Sprintf(
    	"UxSettingsModel[DisplayedInstallmentOptions=%v, AdditionalProperties=%v]",
    	u.DisplayedInstallmentOptions, u.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for UxSettingsModel.
// It customizes the JSON marshaling process for UxSettingsModel objects.
func (u UxSettingsModel) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(u.AdditionalProperties,
        "DisplayedInstallmentOptions"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(u.toMap())
}

// toMap converts the UxSettingsModel object to a map representation for JSON marshaling.
func (u UxSettingsModel) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, u.AdditionalProperties)
    if u.DisplayedInstallmentOptions != nil {
        structMap["DisplayedInstallmentOptions"] = u.DisplayedInstallmentOptions
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for UxSettingsModel.
// It customizes the JSON unmarshaling process for UxSettingsModel objects.
func (u *UxSettingsModel) UnmarshalJSON(input []byte) error {
    var temp tempUxSettingsModel
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "DisplayedInstallmentOptions")
    if err != nil {
    	return err
    }
    u.AdditionalProperties = additionalProperties
    
    u.DisplayedInstallmentOptions = temp.DisplayedInstallmentOptions
    return nil
}

// tempUxSettingsModel is a temporary struct used for validating the fields of UxSettingsModel.
type tempUxSettingsModel  struct {
    DisplayedInstallmentOptions []int `json:"DisplayedInstallmentOptions,omitempty"`
}
