// Package splititwebapiv3
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// VerifyAuthorizationResponse represents a VerifyAuthorizationResponse struct.
type VerifyAuthorizationResponse struct {
    IsAuthorized         bool                   `json:"IsAuthorized"`
    AuthorizationAmount  *float64               `json:"AuthorizationAmount,omitempty"`
    Authorization        *AuthorizationModel    `json:"Authorization,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for VerifyAuthorizationResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v VerifyAuthorizationResponse) String() string {
    return fmt.Sprintf(
    	"VerifyAuthorizationResponse[IsAuthorized=%v, AuthorizationAmount=%v, Authorization=%v, AdditionalProperties=%v]",
    	v.IsAuthorized, v.AuthorizationAmount, v.Authorization, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for VerifyAuthorizationResponse.
// It customizes the JSON marshaling process for VerifyAuthorizationResponse objects.
func (v VerifyAuthorizationResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "IsAuthorized", "AuthorizationAmount", "Authorization"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the VerifyAuthorizationResponse object to a map representation for JSON marshaling.
func (v VerifyAuthorizationResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    structMap["IsAuthorized"] = v.IsAuthorized
    if v.AuthorizationAmount != nil {
        structMap["AuthorizationAmount"] = v.AuthorizationAmount
    }
    if v.Authorization != nil {
        structMap["Authorization"] = v.Authorization.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for VerifyAuthorizationResponse.
// It customizes the JSON unmarshaling process for VerifyAuthorizationResponse objects.
func (v *VerifyAuthorizationResponse) UnmarshalJSON(input []byte) error {
    var temp tempVerifyAuthorizationResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "IsAuthorized", "AuthorizationAmount", "Authorization")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.IsAuthorized = *temp.IsAuthorized
    v.AuthorizationAmount = temp.AuthorizationAmount
    v.Authorization = temp.Authorization
    return nil
}

// tempVerifyAuthorizationResponse is a temporary struct used for validating the fields of VerifyAuthorizationResponse.
type tempVerifyAuthorizationResponse  struct {
    IsAuthorized        *bool               `json:"IsAuthorized"`
    AuthorizationAmount *float64            `json:"AuthorizationAmount,omitempty"`
    Authorization       *AuthorizationModel `json:"Authorization,omitempty"`
}

func (v *tempVerifyAuthorizationResponse) validate() error {
    var errs []string
    if v.IsAuthorized == nil {
        errs = append(errs, "required field `IsAuthorized` is missing for type `VerifyAuthorizationResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
